### ISSUE TITLE
Fork intents from instance to another

### ISSUE THREAD

**Issue by Seraf** [wit-ai/wit#102]
Hello,

Is it possible to query the api to "clone" intent from the instance of another user to my instance ?

I need this feature to let people creating plugins using with and let everyone clone it easily (instead importing corpus).

Thanks

**Comment by saikota** [comment]
Hello, do you have any news on this feature.

**Comment by blandinw** [comment]
So sorry for the late reply and lack of updates. 😔
A lot of things happened since the creation of this issue. We joined FB, we built M and we released Bot Engine. Now, we've been spending a lot of time on the design of community/sharing features in Wit. The release of Bot Engine opens up new possibilities like sharing of bots, entities, etc. This is what we're focusing on for the foreseeable future.

I hope this has helped shed light on the matter. I'm closing this particular issue for now 😊
