### ISSUE TITLE
My app continuously showing me "Traning status : ongoing"

### ISSUE THREAD

**Issue by himanshuteotia** [wit-ai/wit#1049]
Recently, I am facing so many issues with wit.ai. Now I can not even train my app on wit.ai dashboard. It is continuously showing me "Traning status: ongoing". A few days ago, one of my app was deleted automatically. I don't know what is happening in wit.ai but its very worst experience for me.Sometimes  it shows me you could not validate the expression.
![wit ai member_my_3](https://user-images.githubusercontent.com/10083136/38716756-133e5840-3f15-11e8-80f8-0b7e105c4382.png)

**Comment by himanshuteotia** [comment]
This is my app id : `5a9fa28f-5cfb-4dcf-932f-aa5a3390e18d` which was deleted automatically. 

And this app id : `5ab0d7e3-58c6-4fa5-b5d9-12e1183d212f` for which is continuously showing me "Traning status: ongoing"

**Comment by l5t** [comment]
You app should be trained now. And we will report back on the one that disappeared

**Comment by rshenoyfb** [comment]
Regarding app deletion, this occured before, it was due to a delete command which was issued to delete a value, but ended up deleting the app. Can you please send us any delete value command you executed? We can retreive the app, but it would be good to understand and fix the root cause. Can you send us the command which you were using when the app got deleted?

**Comment by himanshuteotia** [comment]
Hi Rajesh, the story of the lost app ( though the app was lost from the dashboard but was showing in this request  https://api.wit.ai/apps?limit=9 ). However, the app suddenly appeared after reporting to you a few days back via email and surprisingly disappeared again on 11th April 2018. FYI, the app appeared but I wasn't been able to work on that. So, please help me to solve the mystery

**Comment by rshenoyfb** [comment]
@himanshuteotia  I have recovered your app. There is an issue in your side which is triggering a bug in our system. You are deleting an entity during your processing. Is there a way you can not run the deletes?

**Comment by blandinw** [comment]
@himanshuteotia we'll get this fixed asap, thank you for patience

**Comment by stopachka** [comment]
Hey @himanshuteotia 

Thank you for reporting this, and apologies for the technical issues you've been dealing with. We are working on uncovering the root cause of your bug. Feel free to continue using as is, we will be monitoring your app, and if there are any issues with it disappearing down the road, we'll be on it to fix asap
