### ISSUE TITLE
The incorrect interpretation of datetime in some cases

### ISSUE THREAD

**Issue by espdev** [wit-ai/wit#1085]
For example, the following cases are interpreted incorrectly by **wit/datetime** entity:

* `[in] Feb 2014` -> `01.02.2014, 1:00:00`. This is not correct.  There should be **interval** `from 01.02.2014, 0:00:00 to 28.02.2014, 23:59:59`.
* `in 2015` -> `01.01.2015, 0:00:00`. This is not correct. There should be **interval** `from 01.01.2015, 0:00:00 to 31.12.2015, 23:59:59`.
* `since 1999` -> `from 01.01.1999, 0:00:00 to -`. There should be `from 01.01.1999, 0:00:00 to NOW` (the same as `from 1999 till now`)
* `after 2001` -> `from 01.01.2001, 0:00:00 to -` . There should be `from 01.01.2002 to NOW`. after **2001** it meens that we consider all the events starting from **2002**
* `from 2005 till 2006` -> `from 01.01.2005, 0:00:00 to 01.01.2007, 0:00:00`. This is incorrect interval. There should be `from 01.01.2005, 0:00:00 to 31.12.2006, 23:59:59`
* `until/before 1920` -> `from- to 19.05.2018, 19:20:00`. This is not correct. There should be `from - to 31.12.1919` (or 01.01.1920). Also `until feb 1920` works fine -> `from- to 01.02.1920, 0:00:00`

**Comment by l5t** [comment]
Thanks for posting. We manage datetime via duckling, which is open source here: https://github.com/facebook/duckling

[in] Feb 2014 -> 01.02.2014, 1:00:00. This is not correct. There should be interval from 01.02.2014, 0:00:00 to 28.02.2014, 23:59:59.: LL you can use the grain for that

in 2015 -> 01.01.2015, 0:00:00. This is not correct. There should be interval from 01.01.2015, 0:00:00 to 31.12.2015, 23:59:59. LL same, you can use the grain for that

since 1999 -> from 01.01.1999, 0:00:00 to -. There should be from 01.01.1999, 0:00:00 to NOW (the same as from 1999 till now) LL you can do it in your side (if nothing in the internal upper limit, then NOW) but feel free to do a PR in duckling

after 2001 -> from 01.01.2001, 0:00:00 to - . There should be from 01.01.2002 to NOW. after 2001 it meens that we consider all the events starting from 2002 LL: good catch, can you submit a PR in duckling

from 2005 till 2006 -> from 01.01.2005, 0:00:00 to 01.01.2007, 0:00:00. This is incorrect interval. There should be from 01.01.2005, 0:00:00 to 31.12.2006, 23:59:59 LL As for the interval, we decided to always have an exclusive upper limit. We may change this in the future as we've received a lot of feedback on this. There is a "grain" field that should help you infer the inclusive upper limit.

until/before 1920 -> from- to 19.05.2018, 19:20:00. This is not correct. There should be from - to 31.12.1919 (or 01.01.1920). Also until feb 1920 works fine -> from- to 01.02.1920, 0:00:00  LL can you open an issue in Duckling or contribute to fix, it seems that this is capture by the hour rule
