### ISSUE TITLE
Roles and Intent not being returned after training through /samples endpoint

### ISSUE THREAD

**Issue by Nyxter** [wit-ai/wit#1103]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
No entity roles or intent are being detected in sentences that the bot had been used to train with. Only plain entities

The roles and intent show within the 'entities' page, on list of trained sentences, but do not appear in results through either wit.ai testing tool, or through the API.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Send many samples to '/samples' endpoint containing intents, and  entities with roles.
For proof of concept I only used one role within the entities, but have also tried it with more previously.
Wait short period for app to train.
Test using a sentence, exactly matching a training sample containing role.

- No intent returns
- No role provided

For these current examples I have only got one entity f each type, rather than multiple entities of the same type, but I imagined role would be returned regardless. 
Additionally I think  whe npreviously playing around with multiple entities that the same issue arose. I can easily put the bot in such a state if requested.

**What is the expected behavior?**
The intent to be returned when tested,
The role to be included when returning the entities.

**What is the App ID where you are experiencing this issue (if applicable)?**
5ae1e4c6-a4d0-42ef-8219-2f3e8a26eec85ae1e4

Additional info:
I think the intent MAY appear if I manually go through and click validate on each of the post, but will need to verify this if you desire.

The screenshot below shows the issue:
The top left shows testing through browser, showing only entity names, no roles 
bottom left shows testing through endpoint (using postman), showing entity names no roles
right hand side shows the training sentences. This included entities with roles, and intents for the same sentence.

Out of screenshot: Green dot appears, saying it is ready, and is not processing.

![image](https://user-images.githubusercontent.com/2597459/40927951-00dccda4-6818-11e8-9e18-b646dc07dfba.png)

**Comment by aforaleka** [comment]
Hi @Nyxter! Thanks for reporting the issue, I don't see the app with the App ID you provided, but if you're referring to the app named fb-WRVUI-test, we actually suspended the related POST /samples calls last night because of unexpected traffic / heavy usage. Can you tell us about your use case (either here or email if you prefer) and we can work with you?

**Comment by Nyxter** [comment]
Hi , Thanks for your reply.
Firstly, no, this is a different issue.
This was purely for the 'MyFirstApp' project.

For the app, the 'Test how your app understands a sentence' does not return any roles , or intents. Purely the entity name.
![image](https://user-images.githubusercontent.com/2597459/40963132-81ff771a-689f-11e8-891c-b3ff1dd093cc.png)

This shows the same sentence in 'Expressions view' having been trained with an intent and role, (and many similar sentences), but neither the intent, or entity role being returned when querying through 'test how your app understands a sentence.

Secondly : 
Regarding the suspended post/samples, I will e-mail you :) 

Sorry for all the posts here!!

**Comment by stopachka** [comment]
Hey @Nyxter, 

I am assuming this issue is about MyFirstApp, with the app-id: 5ae1e4c6-a4d0-42ef-8219-2f3e8a26eec8

Taking a quick look, it looks like the roles are working: 

![image](https://user-images.githubusercontent.com/984574/41247540-1c810f8e-6d63-11e8-88e3-582a16d55337.png)


This may be because of training lag. We are releasing a feature soon that will make this much clearer. Let me know if above is not what you expect, or I am missing something
