### ISSUE TITLE
problem with sharing apps

### ISSUE THREAD

**Issue by vcnsiqueira** [wit-ai/wit#1171]
Hi folks,

I am experiencing a problem with wit.ai. Recently (yesterday) I created an app and shared it with some colleagues to collaborate. But wit do not allow them to edit anything in this new app.

For instance, I created the app with id number 1565467710248684. As the owner of the app, I can edit and create new entities. But I shared this app with other friends and they can not make anything.

Can you help us?

**Comment by blandinw** [comment]
@vcnsiqueira did they receive the email confirmation and clicked the provided link?

**Comment by vcnsiqueira** [comment]
Yes. They received the email and clicked on the button. They still can't make any changes in the app.

**Comment by vcnsiqueira** [comment]
I have some other apps created earlier and they work nicely. The problem happens with all the new apps created. Please, help me!

**Comment by Chaosfirebolt** [comment]
We are experiencing similar issues, so i'll post here, instead of opening new one.

One of my colleagues exported data from another app, created new app with the zip file and shared the app with me. I received notification email and clicked the provided link. The issues are as follows:

**1.** I only have access to the Uderstanding tab, no access to settings, inbox or logs tabs.
**2.** I can't delete or edit entities.
**3.** The input field in the UI, where you train your bot is inactive for me, it is active for the app owner.
**4.** Non of the samples were transfered to the new app. There are no samples in the UI, get samples request from HTTP API also returns an empty array.

App id - 2099975760075757

**Comment by 91ns** [comment]
I have the same issues

**Comment by stopachka** [comment]
Hey all, problem has been identified. Working on a fix. Will update here when in production

**Comment by stopachka** [comment]
hey all, the fix has landed, and you should be able to view shared apps now. Let us know if you still see issues!
