### ISSUE TITLE
Composite Entity Not working

### ISSUE THREAD

**Issue by azeeraazeez** [wit-ai/wit#1197]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
 Bug.
**What is the current behavior?**
Training of composite entities are not working. In my app i have trained for these expressions multiple times
![image](https://user-images.githubusercontent.com/42526981/44317204-86cafb80-a462-11e8-82fe-ebc63283466e.png)
However the sub entities are not being recognised. or sometimes the main composite entity is not being recognised. This is making this feature highly unreliable.
![image](https://user-images.githubusercontent.com/42526981/44317306-18d30400-a463-11e8-847d-fcb8445fa9d1.png)

as i see from other threads in the forum (cc #1183, cc #1163) you have fixed these issues by deploying a fix. However, i dont see any changes affected by this and the issue persists

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

Reliable working of composite entity

**What is the App ID where you are experiencing this issue (if applicable)?**
5b641aea-2429-4ad3-bf8a-8a2e75150e09

**Comment by jtliao** [comment]
Sorry for the delay, we will look into this

**Comment by jtliao** [comment]
Hi @azeeraazeez , after taking a look, for your "Junior Savings" value under "savingsProductName", you have synonyms that include SGD in the name, so "sgd junior saving" is just resolving to "savingsProductName" instead of "currency" + "savingsProductName"

I'd recommend removing the currencies from values under savingsProductName

**Comment by azeeraazeez** [comment]
Hi,

while problem has been closed for SGD. it persists for all other product combinations. please mark this issue as open. 

<img width="1099" alt="screen shot 2018-09-06 at 10 44 27 am" src="https://user-images.githubusercontent.com/42526981/45132008-df6bf980-b1c1-11e8-8be9-8713654942e8.png">

**Comment by jtliao** [comment]
This is likely since all your samples are validated with "what is" or "what are" at the beginning, while the sample you showed above uses "whats", which hasn't been validated at all. See screenshot below with "what is my jpy saving balance"

![screen shot 2018-09-10 at 10 06 22 am](https://user-images.githubusercontent.com/13305586/45312566-4ac70b80-b4e1-11e8-949a-58262d02aecb.png)

**Comment by azeeraazeez** [comment]
Even in the sample provided below it has picked up only currency and not product group. The composite entity was supposed to pickup both its sub entities.

Additionally, is nt the ai smart enough to understand whats as a variant of what is?

**Comment by jtliao** [comment]
Take a look at your validated sample:
<img width="1197" alt="screen shot 2018-09-10 at 8 09 27 pm" src="https://user-images.githubusercontent.com/13305586/45335710-7a9ffe80-b535-11e8-92cb-0aa455f03b54.png">

productGroup is not in your validated sample
