### ISSUE TITLE
Built in NLP on Messenger webhooks returns only error

### ISSUE THREAD

**Issue by geracam** [wit-ai/wit#1239]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**
We've subscribed our app to built in NLP events (no custom models), which adds a "nlp" key to all incoming webhooks.

Since yesterday or so for us, the built in nlp key value is the following for everything:
```
nlp: { errors: [ { code: 'unknown',
message: 'Something went wrong. We've been notified' } ] } }
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Subscribe a messenger app to built in NLP. Any incoming webhook will then have the nlp key with the errors only payload:

```
nlp: { errors: [ { code: 'unknown',
message: 'Something went wrong. We've been notified' } ] } }
```

**What is the expected behavior?**
That entities would be returned. We've tried on the following entities:

wit/phone_number
wit/email

**What is the App ID where you are experiencing this issue (if applicable)?**

The Facebook app ID (not the Wit app id as it is built in entities not custom) is 171971753413838

**Comment by geracam** [comment]
Addendum, opened up this issue per request from the Messenger dev group https://www.facebook.com/groups/messengerplatform/permalink/711577815885864/

**Comment by jtliao** [comment]
hey @geracam , we've found the issue and will look to deploy a fix soon

**Comment by jtliao** [comment]
@geracam this should be resolved now, can you let me know if you still see the issue?

**Comment by geracam** [comment]
@jtliao looks good from our end! thank you so much for addressing!

**Comment by MagSag** [comment]
**Do you want to request a feature, report a bug, or ask a question about wit?**
Report a bug

**What is the current behavior?**
We've subscribed our app to built in NLP events (no custom models), which adds a "nlp" key to all incoming webhooks.

The built in nlp content when console.logged is :

nlp: { errors: [ { code: 'unknown',
message: 'Something went wrong. We've been notified' } ] } }

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Subscribe a messenger app to built in NLP. Any incoming webhook will then have the nlp key with the errors only payload:

nlp: { errors: [ { code: 'unknown',
message: 'Something went wrong. We've been notified' } ] } }

**What is the expected behavior?**
Return Entities

**What is the App ID where you are experiencing this issue (if applicable)?**

1460880240681105 (WIT)

**Comment by stopachka** [comment]
Hey @MagSag 

Took a quick look, and I see very few exceptions on your app. Do you mind opening up a new issue, and describing in detail
- on what messages this triggers
- if this triggers consistently
