### ISSUE TITLE
Intent matching issue

### ISSUE THREAD

**Issue by sushant0077** [wit-ai/wit#1294]
**When a sentence is matching to 2 different intents with different confidence level, it should ideally match to the high Confidence Level, but got matched to the lower one and message was sent wrongly. Please see below ss.
Bot Reply Col.png
![bot reply col](https://user-images.githubusercontent.com/8425318/49283365-91f8e300-f4b7-11e8-8d92-7b77f57d13b8.png)

Also, when a sentence has different keywords and are matching to same intent still wit does not give expected reply. Attached is the ss for this scenario.
Yes_Response.jpg
![yes_response](https://user-images.githubusercontent.com/8425318/49283377-97eec400-f4b7-11e8-9205-18bddaaf4db7.jpg)

We are facing these issues quite frequently. Please can give a solution asap.*

**Comment by jtliao** [comment]
Regarding multiple intents, this is intended behavior, as there are many cases where we want all the relevant intents to be returned. You would likely have to do some parsing on your end to get the max confidence intent. 

I don't quite understand your second scenario, can you lay out the expected behavior v.s. current behavior?

**Comment by jtliao** [comment]
Feel free to re-open if you have more details
