### ISSUE TITLE
Matching keyword as suffix/prefix (Hebrew)

### ISSUE THREAD

**Issue by shasha79** [wit-ai/wit#1306]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
Keyword is matched as a prefix or suffix of another word
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
This is the text:
יש לי הרגל
I have a keyword (גל) which is matched inside another (completely unrelated) word: הרגל
**What is the expected behavior?**
Keyword shouldn't be matched as prefix or suffix of another word
**What is the App ID where you are experiencing this issue (if applicable)?**
58741228-a551-45b4-a33e-1a79c5fc04c3

**Comment by jtliao** [comment]
We'll look into this. Just to confirm, since we don't have anyone who understands Hebrew on the team, would this be similar to matching the keyword "he" in "hello there"?

**Comment by shasha79** [comment]
Right. BTW both times it happened with 2-letter words (both as a suffix and
as a prefix)

**Comment by patapizza** [comment]
Hi @shasha79, sorry for the latency on this one.

It seems like the keyword isn't showing up anymore. How did you solve the issue?

<img width="973" alt="screen shot 2019-02-15 at 5 15 57 pm" src="https://user-images.githubusercontent.com/1015208/52892237-7fe92100-3145-11e9-8710-b3bea32545e9.png">


Feel free to reopen if the issue comes back. Thanks.
