### ISSUE TITLE
keyword lookup strategy not working as expected

### ISSUE THREAD

**Issue by maxim-isakov-ross** [wit-ai/wit#1326]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
We have an entity called "jurisdiction" that has the lookup strategy "keyword". Many of the keywords we have for the "jurisdiction" entity do not get detected, even though they are exact matches to the keywords present in the entity.

Example:

Are dogs cats in Pennsylvania?

Response:

{
  "_text": "Are dogs cats in Pennsylvania",
  "entities": {},
  "msg_id": "w9dwj193nda9w3aw3"
}

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

It should detect Pennsylvania as a jurisdiction entity, especially because on my understanding of how the "keyword" lookup strategy works.

**What is the App ID where you are experiencing this issue (if applicable)?**

1991960120926083

**Comment by aforaleka** [comment]
Hey @maxim-isakov-ross, thank you for reporting. I took a look at your app and it seems like no samples have been added, which the app needs in order to start training and recognizing entities.

If you validate a sample say "Are dogs cats in Pennsylvania?" with "Pennsylvania" annotated as the jurisdiction entity, it will kickstart training and your app can recognize the jurisdiction entity in sentences once the training is done. Same for the other entities, you'll have to first add samples that include them. Hope that helps!
