### ISSUE TITLE
Wit console/API not working

### ISSUE THREAD

**Issue by jtliao** [wit-ai/wit#1379]
Using this to track issues with Wit console/API. we are actively working on fixing this

**Comment by Mukhammadali** [comment]
Guys, I am receiving this kind of error on multiple APIs

![image](https://user-images.githubusercontent.com/22298895/54314423-71374200-45fd-11e9-9366-04fcf86bd8a9.png)

**Comment by klemensz** [comment]
Same issue here...

![Bildschirmfoto 2019-03-13 um 18 57 06](https://user-images.githubusercontent.com/1116517/54318499-d7fd3100-45e6-11e9-90a3-ee2657308cdd.png)

**Comment by ngoral** [comment]
I receive `408 (Request Timeout)` all the time. It was not so before, is it because of this issue?

**Comment by b-tix** [comment]
Same problem using the gui for training, but not all the time. I cannot find out whats going on. Since March 13th it appears while training. Yesterday training stuck in state "ongoing". It's app ID 2371065689592980

<img width="377" alt="Bildschirmfoto 2019-03-13 um 20 38 50" src="https://user-images.githubusercontent.com/48549922/54345825-1ffe7100-4644-11e9-98c3-c24f9b882288.png">

**Comment by b-tix** [comment]
Is there a bigger problem? After sharing my app with an github account it is shown as shared but the followging url ist open https://wit.ai/null/AppName where AppName is the correct name of my app. "What you were looking for could not be found" is the message now. What about the "null" and how to fix it?

**Comment by jtliao** [comment]
This should be resolved now, I think most of the issues outlined in this thread were a result of the issue.  Unfortunately we were affected by the same issue that brought down Facebook for a significant period yesterday. 

We sincerely apologize for the inconvenience.
