### ISSUE TITLE
Issues with wit/contact

### ISSUE THREAD

**Issue by praharshbhatt** [wit-ai/wit#1394]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug(?)

**What is the current behavior?**
I've set intent "Call" and entity "Wit/Contact"
the intent is suggested correct mostly, but wit never gets "Wit/contacts" correct.
For example: "Call boss", or "Call Chetan" Even after training with the same sentence multiple times.

To tackle this, I also declared a new user-defined entity "contact_name", but the same problem persists.

Point to note is in 20% cases when "Wit/contact" is assigned correctly, it is on American names like "john" or "paul".

**What is the expected behavior?**
wit should get all the names correctly and assign the entity "Wit/Contact" to it

**What is the App ID where you are experiencing this issue (if applicable)?**

5af134f9-929b-4f9c-b496-1eed315571e2

**Comment by patapizza** [comment]
Thanks for reporting, we'll need to improve the model for `wit/contact`.

**Comment by truelossless** [comment]
I also have noticed that some cities in my model are picked as wit/contact instead of wit/location, despite the fact that I trained specifically this sentence so that the city is chosen as wit/location.
The wit/contact entity just keep coming back.

**Comment by patapizza** [comment]
Which examples?

**Comment by truelossless** [comment]
The sentence "J'habites à Nantes" (I live in Nantes) keeps labeling Nantes as wit/contact even though in my model it is set as wit/location

example:
![image](https://user-images.githubusercontent.com/31276570/56813536-719e3c00-683d-11e9-8449-a87db30ce84b.png)

in my samples:
![image](https://user-images.githubusercontent.com/31276570/56813613-9eeaea00-683d-11e9-808c-ef386072e936.png)

But some cities work as expected:
![image](https://user-images.githubusercontent.com/31276570/56813753-e7a2a300-683d-11e9-9691-e813960ef9c9.png)


One simple fix would be to let people restrict entities for every intent. Because if I delete wit/contact of my app, the wit/location entity is picked.

**Comment by jtliao** [comment]
We'll explore how we can address this.

**Comment by praharshbhatt** [comment]
Update: Now the "Wit/Contact" has gotten progressively better!
Still not accurate enough, "Wit/Reminder" keeps interfering, but gives around 50% accuracy. (it was far lower in the past)

**Comment by jtliao** [comment]
Merging with #1615 for tracking
