### ISSUE TITLE
App status stuck in ONGOING

### ISSUE THREAD

**Issue by 51100807** [wit-ai/wit#1402]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Report a bug

**What is the current behavior?**

My app is stuck in ongoing status for several weeks. Looks like something is not right because I’ve commented on a similar topic but my problem is still not solved.

**What is the expected behavior?**
My app status must be done

**What is the App ID where you are experiencing this issue (if applicable)?**
5add9b65-6776-487f-aec9-cd1c45a2d70e

**Comment by patapizza** [comment]
Hi @51100807, your app is very big and we are working on a plan to handle large apps like yours (this is similar to https://github.com/wit-ai/wit/issues/1338#issuecomment-461556181). Please bare with us while we work on improving our machine learning infra.

**Comment by 51100807** [comment]
Hi @patapizza , thank you for your kind reply. I am downsizing my app now. 
May I know the the limit number of intent one app can handle? And may I know when can wit handle large apps?

**Comment by patapizza** [comment]
Thank you for your patience and understanding. There isn't a hard limit but it depends on the total size of the dataset. We've prioritized the work but aren't able to provide an estimate yet.

**Comment by Andrew1294** [comment]
Our app (mine and my collaborator's) is stuck on Ongoing for a few hours, could you restart it please?
Last sentence I validated before it stuck was "My name is fehui".
In order to train the wit/contact to identify 'fehui' as a contact (which is an username in my app)
Our app link is https://wit.ai/NC0DER/NeoJira.ai/entities

**Comment by sophiexr** [comment]
hi @patapizza, do you have a time frame as to when this issue will be resolve? We rely a lot on this app and it's stuck on training again since June 4th...  
thanks

**Comment by patapizza** [comment]
We should be able to improve these apps in a couple of weeks.
Thanks for your patience.

**Comment by arghya052** [comment]
Hi,

My app got stuck in training.  Status showing as Ongoing for an hour now.

App Id : 2460764473976354.

Can you please refresh it from backend if possible?

Thanks,
Arghya

**Comment by arghya052** [comment]
Hi @patapizza,

My app is having just 3 user defined intents but still the training is getting stuck. Now it is showing as Scheduled to train at 3:46 PM IST which is like 6 hours from now. Can you please look into this since we are rolling out a new feature today.

Thanks, 
Arghya

**Comment by sophiexr** [comment]
Hi @patapizza,

Any news on that issue? Our app is stuck on Ongoing since June 30th...

Thanks

**Comment by kingseaeast** [comment]
Hi @sophiexr,

I've forced a retrain for your app. Please check if it fixes your issue.

**Comment by sophiexr** [comment]
hi @kingseaeast 

The app didn't train. It still shows as ongoing and  last_trained_at: "2019-06-30T14:11:19-0700" 

thanks

**Comment by asfyra** [comment]
Hi @patapizza, we are working on the same project with @sophiexr. We hoped that by changing this issue's status to closed, the issue with apps being stuck during training would have been resolved. 
If this is the case could you please check why out application is still stuck.
@kingseaeast as @sophiexr mentioned last week our app with id: 5b1e505b-0e5f-484a-9e44-20d7c4ee12d1, is still stuck.

Best Regards
Alex

**Comment by patapizza** [comment]
Hi @asfyra, your app has too many samples. We're still actively working on improving our infra to support large apps like yours. Thanks for your patience!

**Comment by sophiexr** [comment]
Hello again,

 @patapizza, thanks for your reply. 

I was wondering what exactly do you mean by samples... will it help if we delete sample questions without entity ? (I validate questions without entity when we plan to create an answer for those questions in the near future, but since our app is not training we haven't created any new entities yet). 
Also how about the validated sample questions with entity, If I remove those all the training will be lost, right? 

thanks again for all your help and all the info you provide. This app is really important for our organization and we're really looking forward for this issue to be resolved.

**Comment by sophiexr** [comment]
hi @patapizza  @kingseaeast

Kind reminder....
thanks
