### ISSUE TITLE
max audio length is too short

### ISSUE THREAD

**Issue by kevinours** [wit-ai/wit#1405]
Hello,

Is there a way to increase max audio lenght ? 20 sec is really short.

thank you !

**Comment by aforaleka** [comment]
Hi @kevinours, we have this limit since we see speech recognition quality declines significantly after 20s. As our top priority is to ensure the service is stable, we have this cap until we find other solutions. Wit's key use case is also for shorter messages and we think that a lot of words can be captured in 20s. Thank you for your understanding.
