### ISSUE TITLE
Intent not recognizing

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1506]
Hi team, 
I have an intent "get_info".
The following input "tell me about uib" is not recognizing as intent "get_info" even though it is an example for the same intent.

My appId is 2249860545110846.

Please help in fixing.

Thanks in advance
Anjaly

**Comment by FengyangZhang** [comment]
Hi Anjaly,

Thanks for contacting us. I think the app got confused because you have another expression "tell me about tech" with value "used_technologies", while "tell me about uib" is of value "get_info". 

A suggested way to do this is to have a single value under intent, say "get_info" for all the "tell me about xxx" expressions, and have another keyword entity to capture words like "uib" and "tech".
