### ISSUE TITLE
Entity not recognizing

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1507]
Hi team,

We have an intity 'geoLocations' which have a value 'kochi' with synonym 'cochin' (free-text and keywords) . But when we check the following command 'time in cochin' it is not recognizing the 'geoLocations' entity.

Please help us to fix this.

Thanks in Advance
Anjaly

**Comment by FengyangZhang** [comment]
Hi Anjaly, 

We are happy to look into this issue, can you provide us with the appid? Thanks!

**Comment by anjaly** [comment]
Hi @FengyangZhang 

Our appid is 2249860545110846

**Comment by FengyangZhang** [comment]
Thanks for the information! So my guess is because there're both wit/location(builtin) and geoLocation(user-defined) in your app, some locations like 'cochin', 'kochi' and 'ernakulam' will get recognized by wit/location.

If you want to recognize a predefined list of geo locations, you can just remove wit/location entity and update the geoLocation entity.

Let me know if you have other concerns.
