### ISSUE TITLE
My bot is showing that training is scheduled, how to force training now

### ISSUE THREAD

**Issue by YaserMarey** [wit-ai/wit#1508]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by FengyangZhang** [comment]
Hi YaserMarey,

There's currently no way to force training when training is scheduled. Can you provide the appid so we can look into this issue?

**Comment by arghya052** [comment]
Hi Team,

We are also facing the same issue here since yesterday. The training is always showing as "Scheduled".

App ID : 2460764473976354

Training is always getting scheduled to a time 6-7 hours later. This is becoming very difficult since we are unable to deploy the new features which requires new intents.

Please look into the issue and advise.

Regards,
Arghya

**Comment by arghya052** [comment]
Hi Team,

Any updates on this? This issue was not there previously. All trainings were started almost instantaneously. Now every time the training shows as "Scheduled". Please look into the issue and advice.

Regards,
Arghya

**Comment by lycai-fb** [comment]
Hey @arghya052,
The logs show that your app has been successfully training (latest trained 7/19 @6:15AM).
I'll close this task, but please open another one if you are still hitting this issue.
Thanks.
