### ISSUE TITLE
AI-Smart Mirror tutorial

### ISSUE THREAD

**Issue by Devan0369** [wit-ai/wit#1538]
I am basically tryout a tutorial on AI-Smart Mirror by Hacker Shack - and they use Wit.ai - in the tutorial they suggest uploading a pre-zipped file with all their source including app.json file - to get an api key - I am just uploading the file wit_training_data.zip as suggested. to create an new app. so when I click create it show instead a failed Parser app.json error message. Why is this so? and how to fix it? 
their username on wit.ai is aarontainter/Smart-Mirror-tutorial

**Comment by aforaleka** [comment]
hi @Devan0369, can you link us the wit_training_data.zip so we can try to reproduce?

**Comment by upendrasingh18** [comment]
I'am also facing same issue can you help in solving this issue @aforaleka .

**Comment by jennygrahamjones** [comment]
@aforaleka The zip file referred to is here: https://github.com/HackerShackOfficial/AI-Smart-Mirror/blob/master/models/wit_training_data.zip

From doing a comparison between this app.json and an app.json file that I have from another Wit app that can be imported, I noticed this difference: 

- Doesn't parse:
`  "zip-command": "zip smart-mirror.zip smart-mirror/app.json smart-mirror/entities/*.json smart-mirror/actions.json smart-mirror/stories.json smart-mirror/expressions.json",`
- Does parse:
`  "zip-command": "zip smart-mirror.zip smart-mirror\/app.json smart-mirror\/entities\/*.json smart-mirror\/actions.json smart-mirror\/stories.json smart-mirror\/expressions.json",`

It doesn't look like this is the only parsing error, which suggests that maybe there are other syntactic differences between the example app in https://github.com/HackerShackOfficial/AI-Smart-Mirror/ and the current syntax that Wit expects when importing an app. Maybe something has changed in the 3 years since the AI-Smart-Mirror repo was last updated?

**Comment by hiradevina** [comment]
I try to change 
"zip-command": "zip smart-mirror.zip smart-mirror/app.json smart-mirror/entities/*.json smart-mirror/actions.json smart-mirror/stories.json smart-mirror/expressions.json",
to 
"zip-command": "zip smart-mirror.zip smart-mirror\/app.json smart-mirror\/entities\/*.json smart-mirror\/actions.json smart-mirror\/stories.json smart-mirror\/expressions.json",
but i still get the error notification. any suggestion?

**Comment by Sanjaysandy** [comment]
[wit_training_data.zip](https://github.com/wit-ai/wit/files/3885217/wit_training_data.zip)
i also could not create app for it

**Comment by jtliao** [comment]
Same as #1592

**Comment by sinemsecgin** [comment]
Help me!

**Comment by Sanjaysandy** [comment]
Hi man you too facing the same problem I have found solution to it plz
contact me at WhatsApp my number is +91 8939511999 ok iam from India

**Comment by PoojaAmin29** [comment]
i am also facing the same issue and i had done the changes in app.json but still it says failed parser app.json

**Comment by sheldon99** [comment]
Any solution to solve this? Facing the same issue as well.

**Comment by Mahieedaboss** [comment]
same

**Comment by jocode** [comment]
Same error. Please help us
