### ISSUE TITLE
Question about free text/keywords

### ISSUE THREAD

**Issue by sducs19** [wit-ai/wit#1559]
I want to ask a question.

I am developing an app that recognizes the activities given in the free text.

eg: I want to play golf tomorrow. OR I am interested in playing golf tomorrow.
Intent: sports (trait)
sports_type: golf (free text & keywords)

I want to be able to recognize other sports as well. I am assuming this can be done but whenever I enter any other sport instead of golf, it picks up the Intent but not the entity.

Am I doing something wrong or should I be doing something else ?

I could list all the different types but then I would need to do that for all the intents that I plan to implement. Is this the only way ?

AppID: 2889976034365524

**Comment by jtliao** [comment]
hi @sducs19, apologies for the delay-- you would need to define the different types of sports here, otherwise the model wouldn't be able to extract them. However, you shouldn't need to re-define them for different intents, the `sports_type` entity should apply to all

See more details here https://wit.ai/docs/recipes#extract-an-entity-that-generally-takes-a-value-in-a-predefined-list-open-enum-but-you-are-open-to-new-values
