### ISSUE TITLE
BUG Settings

### ISSUE THREAD

**Issue by lazyurban** [wit-ai/wit#1604]
After I save a version of app I can't do anything.
https://wit.ai/lazyurban/LazyUrban/settings
**Something** went wrong 😣 Please refresh or create a Github issue here. **

**Comment by jtliao** [comment]
@lazyurban do you mean that saving the snapshot doesn't work? or after saving it, something else doesn't work?

**Comment by lazyurban** [comment]
This is a website issue  
![Screenshot from 2019-11-26 20-50-42](https://user-images.githubusercontent.com/58209724/69663651-53c4de00-108f-11ea-8b65-e6996f731bd6.png)

**Comment by lazyurban** [comment]
The other thing I would like to test Russian and Ukrainian Language.
I got the error { "code": "bad-request", "error": "Speech recognition is not supported for language: uk" } 

Could you please activate this feature?

**Comment by jiayexie** [comment]
Hi @lazyurban, unfortunately we do not support speech for uk yet, and won't be able to support it very soon.

We're unable to find any error logs with your app - could you please describe the detailed steps you did to get to this screen? It also looks like your app is new and empty. Could you try creating a new app and repeating what you did? If it works then great, otherwise we'll be able to get the exact steps to reproduce the error you encountered.
