### ISSUE TITLE
Issue in intent identification

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1610]
Hi team,
I'm having some issues in identifying the intents for similar inputs.
Below are the inputs and their intents
Wer ist im gemeinderat => no intent and entity identified as we haven't trained .
Wer ist der gemeinderat  => identified intent 'weather_info'which is wrong. We haven't trained this input and it is suposed to return no intents and entities.

We have some inputs in intent 'weather_info' hat have 'ist' in the trained examples.

Please help us in fixing this as we are getting inconsistent response for untrained inputs.

Thanks & Regards
Anjaly

**Comment by Xueying-Wang** [comment]
Hi @anjaly can you provide your app ID so that we can look into it?

**Comment by anjaly** [comment]
> Hi @anjaly can you provide your app ID so that we can look into it?

Our appId is 4NSRHQDZC5POCJFZRVOPD5EAOYJ7RAJY

**Comment by Xueying-Wang** [comment]
Hi @anjaly we looked into your app and think it's working normally. When your wit app sees an untrained input, it would make the best prediction based on examples you've trained. The best way to let your app know different untrained inputs belong to or not belong to the same intent is to train them with correct intents/entities and train similar examples as well. 

Specifically, when typing in 'Wer ist der gemeinderat', you can see that the confidence for 'weather_info' is not high, because there is no similar trained input yet. To make your app do better at predicting what's not intent 'weather_info', you would need to train more inputs that's not 'weather_info'. And same with 'bad_words'.

You can also check out the negative samples section of our docs for more information: https://wit.ai/docs/recipes#manage-negative-samples

Please let us know if this answers your question

**Comment by anjaly** [comment]
> Hi @anjaly we looked into your app and think it's working normally. When your wit app sees an untrained input, it would make the best prediction based on examples you've trained. The best way to let your app know different untrained inputs belong to or not belong to the same intent is to train them with correct intents/entities and train similar examples as well.
> 
> Specifically, when typing in 'Wer ist der gemeinderat', you can see that the confidence for 'weather_info' is not high, because there is no similar trained input yet. To make your app do better at predicting what's not intent 'weather_info', you would need to train more inputs that's not 'weather_info'. And same with 'bad_words'.
> 
> You can also check out the negative samples section of our docs for more information: https://wit.ai/docs/recipes#manage-negative-samples
> 
> Please let us know if this answers your question

Thankyou @Xueying-Wang for the reply. We tried by adding negative samples in our appId 3289645331108228. 
'Wer ist der gemeinderat' worked but 'Wer ist Oberbürgermeister' identified 'city_maintenance'.
The negative samples have examples starting with 'Wer ist'. 
Can u please let us know the reason behind this and how to fix this.

**Comment by Xueying-Wang** [comment]
@anjaly Thanks for your response. I see you point - 'city_maintenance' is tagged in 'Wer ist Oberbürgermeister' but is not in 'Wer ist der gemeinderat'. You probably don't want it tagged in either case. Unfortunately I don't know what exactly causes the predictions for the two specific inputs to be different, but I have some tips on improving your app's performance in general.

I looked into samples under 'city_maintenance' and found that there seem to be many single word expressions under this intent. Intents are used to categorize what people want to perform, so the model would likely perform better if you add more sentences/expressions that convey the complete message. You can always remove samples you don't want anymore from the samples page. Or if you just want to use 'city_maintenance' for extracting key information from single words/expressions, we would recommend creating your own entity for it with freetext and keyword lookup strategy.

I hope this helps!
