### ISSUE TITLE
Stuck in 'Training status: ongoing"

### ISSUE THREAD

**Issue by ayush-ktr** [wit-ai/wit#1642]
Stuck in 'Training status: ongoing"

**Comment by jtliao** [comment]
Hi @ayush-ktr, please provide your app ID, otherwise we won't be able to help you

**Comment by asfyra** [comment]
Hello, i created a new app and laded it with samples.  It is also stuck on training ever since.
AppId: 2841817995840539
could you please help ?

Thank you

**Comment by kingseaeast** [comment]
I have kicked off a retrain, but looking at your app the number of training samples is pretty high and our system will have trouble handling this case. If the current training remains "ongoing", I recommend you reduce the number of training samples to be under 50k.

**Comment by asfyra** [comment]
Thank you @kingseaeast  for your response.
What if the application needs to support lots of trait values and as a result a great amount of samples? 
Is there any alternative to the free version of wit ? Something like an enterprise version, that would be come under some certain subscription cost of course.

**Comment by FengyangZhang** [comment]
@asfyra We don't have an alternative version of wit, but there're things that we can do to support your app training. We do have to make sure there's no regression on the app quality so that would take some time (a few days I would say).

**Comment by asfyra** [comment]
Thank you @FengyangZhang. 
Actually we are looking to expand our bot application even more. Right now we are using a similar project with _appid: 5b1e505b-0e5f-484a-9e44-20d7c4ee12d1_ but due to the issue described [here](https://github.com/wit-ai/wit/issues/1637), we created this new project _(appid: 2841817995840539)_ and combined the two traits to one. The samples are the same in both projects. We exported them from the one and imported them to the new one.
We want to add more trait values and samples to support them, but we we are skeptical, due to the sizing issues and the training procedure.
Of course we would very much appreciate your help on making our application functional and expandable. As this project serves as an FAQ and support bot, the content we would like to add is broad.

Regards
Alex

**Comment by FengyangZhang** [comment]
@asfyra Your app should be able to train now. Note it will take a few hours to train though. To your concern, we are in the process of a migration which will make things more reliable and able to support all use cases. If you see any problem of your app, please reach out!

**Comment by asfyra** [comment]
@FengyangZhang thank you very much
