### ISSUE TITLE
Entity name is no showing

### ISSUE THREAD

**Issue by sabinchacko007** [wit-ai/wit#1662]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
when we add an expression, the entity name is blank

![Screen Shot 2020-03-05 at 6 05 14 PM](https://user-images.githubusercontent.com/36190477/75982299-5051b600-5f0c-11ea-8e06-57c705a6d4ff.png)

**Comment by Xueying-Wang** [comment]
@sabinchacko007 Thanks for reporting the bug. There has been some frontend instability. Can you try refresh and re-login to see if entity names show up?

**Comment by sabinchacko007** [comment]
this is not  a consistent bug , the issue is repeating overtime

**Comment by asfyra** [comment]
We are also encounter this issue for application Id: 2841817995840539
![image](https://user-images.githubusercontent.com/6898230/80464654-c8ec5600-8942-11ea-8a2d-cd1838873359.png)

The same issue applies to the understanding tab too.

Apart from that, our application training stopped being triggered since April 24.
Although we validate samples, training does not schedule to run.
Could you please check what's wrong with this?

Thank you
