### ISSUE TITLE
Non-Dictionary Words

### ISSUE THREAD

**Issue by straley** [wit-ai/wit#168]
Hi,

I'm trying to have the voice recognition handle a non-dictionary brand name.  But, it keeps responding with a word that sounds similar.  For instance, if I wanted it to understand the word "Tark", it might keep returning "Dark".  Is there a way to get the voice recognition to understand custom non-dictionary words? 

Thanks,
Scott

**Comment by l5t** [comment]
Hi Scott,
Thanks for reaching out. We are working on this and more specifically the customization of the acoustic/language models for the Speech engine. This will allow you to train your instance via the Voice Inbox to recognize non-dictionary words. That being said, I will take us at least 6 months to complete.
Laurent

**Comment by sebastien-bratieres** [comment]
+1 for the feature request

**Comment by kundusandeepan** [comment]
+1 for the feature request. 
It is in roadmap? progress? done?

**Comment by sriraman** [comment]
Any Progress?

**Comment by martinraison** [comment]
Hi, apologies for the very late reply and lack of updates. We haven't had a chance to work on the speech engine recently. With the recent release of Bot Engine, we decided to focus our efforts more on the semantic analysis and dialogue parts of Wit.ai rather than the speech recognition, so it is unlikely that there will be any updates on this front in the foreseeable future.
