### ISSUE TITLE
Doubts with Intention Greetings (SCORE always 1)

### ISSUE THREAD

**Issue by mauridengo** [wit-ai/wit#1768]
*question*

I am using WIT.AI and I created a greeting intention Ex. Hello, Hi, how are you? .. (As I use the Portuguese language so I don't use the greeting that comes with the WIT "Built-in wit / greetings")
I created a new intention, however, I did not create any entity! However, when calling the API it always returns a SCORE of 1 and the greeting intent even for words that have no sense like XYZ for example!
Can anyone tell me what I might be doing wrong?

App ID: 980237075730983

**Comment by wangsnowyin11** [comment]
Checking your app, seems whatever input, it will be predicted into the intent. 

Thanks for reporting! Looking

**Comment by jtliao** [comment]
Hi @mauridengo, so far you've only validated samples with the greetings intent. So, pretty much any utterance you provide will give that intent, since it doesn't know anything else. You should validate some negative samples (e.g. samples without the intent) with phrases that should not trigger the intent, in order to balance it out.

**Comment by mauridengo** [comment]
After following the recommendations above to register negative questions (without intention) it worked correctly! Thank you for your help
