### ISSUE TITLE
Getting 500 errors

### ISSUE THREAD

**Issue by scottpdo** [wit-ai/wit#1788]
I'm using the [Python SDK](https://github.com/wit-ai/pywit), version `20200513` of the API. Sometime in the last few hours requests using `client.message(text)` began returning 500 errors. I haven't changed anything in my code. Is this a server issue on Wit's end?

**Comment by jtliao** [comment]
what is your app ID?

**Comment by scottpdo** [comment]
260232232049310

**Comment by jtliao** [comment]
Your app is beginning to see problems (both in training and prediction) due to the number of entities you have in your app.

From looking at your app, I see that you're using free-text/keyword entities for full sentences -- these should be tagged as values under the intent, since you're not looking to extract specific spans out of the sentence, but rather the overall meaning of the sentence. 

Example:
Before: "What is the weather" was annotated with the whole span as "Weather" entity
Recommended change: "What is the weather" is annotated without span, with "Weather" intent value

**Comment by scottpdo** [comment]
In that case would the intent simply be `intent` and have different values matching the meaning of it the sentence?

**Comment by jtliao** [comment]
Exactly. I'm happy to discuss the specifics for your app in more detail either here, or through e-mail at help@wit.ai if you'd prefer to not have the information shared publicly.
