### ISSUE TITLE
 Wit.ai has a problem loading the .zip file and does not display Utterances.

### ISSUE THREAD

**Issue by stanislawczartoryski** [wit-ai/wit#1795]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by patapizza** [comment]
Hi @stanislawczartoryski,

What is your app ID? Can you be more specific?

Thanks.

**Comment by stanislawczartoryski** [comment]
Hi Julien,

My app id is 618990298698878.

For last week I can't as my team mates download the .zip file with our
data, we get notification that something wet wrong and that You have been
notified.

Second problem is that on Utterances the page jumps out empty, but when I
open app in old version all is in there, although this works it's valid and
shows only the input from me but the other team mates input don't get shown
to eachother.

Best regards
Jakub Czartoryski

pon., 8 cze 2020 o 18:37 Julien Odent <notifications@github.com> napisał(a):

**Comment by KartikChugh** [comment]
Yeah the Utterances page being empty is a bug I've been having for a while (and which the Wit team claimed to be working on a fix for a few weeks ago?)

**Comment by rajathgunners** [comment]
Hi I have been having the same problem too 
My app ID is 1472013426340851.

We are using Wit.ai to detect phishing type of questions like asking for sensitive info in survey forms that are created in our platform and to block those users. But without seeing the utterances coming in, i cannot know how effective wit is doing and whether it needs more training.

And when I try to download the zip file or try API to get Utterances, i get returned this error 
`Entity '260648485195758' not found`

Request the amazing engineers at Wit to fix it so that we can incorporate it into our live environment.

Thanks,
Rajath

**Comment by patapizza** [comment]
@stanislawczartoryski, @rajathgunners I just fixed your apps. We've fixed the root cause a while back, so this shouldn't occur anymore.

**Comment by rajathgunners** [comment]
Awesome Thanks Guys
