### ISSUE TITLE
Adding synonym does not initiate training

### ISSUE THREAD

**Issue by KartikChugh** [wit-ai/wit#1815]
Just as removing a keyword initiates training, adding a synonym to a keyword should as well.
Otherwise, Wit users have to make some artificial tweak to start the training process

**Comment by jtliao** [comment]
Hey @KartikChugh, is the entity you're using free-text, keyword, or free-text + keyword?

Edit: To clarify, removing keywords shouldn't actually trigger training in the first place, since keyword matching is not model based and is reflected as soon as you update the entity. The same follows for adding synonyms.

**Comment by KartikChugh** [comment]
Got it.
