### ISSUE TITLE
Utterances are gone

### ISSUE THREAD

**Issue by patapizza** [wit-ai/wit#1876]
Originally posted in https://github.com/wit-ai/node-wit/issues/210 by @oliverjessner

**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**
Utterances section is empty

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
915460958972821

**Comment by dsokac** [comment]
Hello there, 

when can we expect this bug to be fixed? This is kind of critical, I cannot say how important it is because I would like to have overview on which training phrases . This was a feature in the previous version and how come it is not working now? We would appreciate your response as quickly as possible. Thank you in advance.

@patapizza  hello again hahaha 😄

**Comment by patapizza** [comment]
Hi @oliverjessner @dsokac,

I can see the utterances now: https://wit.ai/apps/915460958972821/utterances

Let me know if you still don't see them.

**Comment by oliverjessner** [comment]
Can confirm they are back. Thank you very much 🦾

**Comment by dsokac** [comment]
I cannot confirm.... why would utterances return there, and not here (  https://wit.ai/apps/2551588624865480/utterances ) ? Please, can you take a look??? It is weird to me why would utterances depend on some specific setup and not applied on all cases but just that one case?
