### ISSUE TITLE
Issue in identifying entity

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#1884]
Hi,

We have an entity product with the below value. Added screen shot with the synonyms we have trained.

![image](https://user-images.githubusercontent.com/601711/90633174-33533a00-e243-11ea-96ed-2afcfabbf9d7.png)

But on user input 'Whatsapp business' it is showing

![image](https://user-images.githubusercontent.com/601711/90633289-6a295000-e243-11ea-94f7-3c7e900fdd69.png)

Why it is not identifying the product entity 'Whatsapp enterprise Access'

SO we trained "whatsapp business" as synonym for '@products:WhatsApp enteprise Access'. After that 'whatsapp business api' is identifying @products:WhatsApp enteprise Access but 'WhatsApp business api' is not.

Does wit consider it as case sensitive manner.

Thanks'

**Comment by FengyangZhang** [comment]
Hi @anjaly, thanks for opening the issue. Can you provide the app ID so I can take a look?

**Comment by anjaly** [comment]
HI,

We have trained the above issues in our original app. 
Attaching the id of the app which we imported earlier 304694880636875

Thanks

**Comment by FengyangZhang** [comment]
Sorry I'm not sure if I understand the question. Seems "whatsapp business" is not added as a synonym for "WhatsApp enteprise Access"?

**Comment by anjaly** [comment]
Hi,
Even if we haven't added 'whatsapp business' as a synonym, we have added 'whatsapp'.
Then on inputting 'whatsapp business' it should identify the entity right?
The same issue occurred for 'can u tell me about pricing'. We have added 'pricing' in intent get_cost.
Please help in resolving.

We are facing similar issues again and again.
'demos' is identifying intent: demo_services but on inputting "can you show me the demos" if is identifying no intents.

It is very urgent as more and more inputs are getting failed.

can someone please help in identifying the issue.

Thanks

**Comment by patapizza** [comment]
Hi @anjaly,

* I don't see `whatsapp business` as a synonym.
* You have `whatsap`, `Whatsapp` and `WhatsApp enterprise Access` as keywords. This is going to confuse the model. 
* Your `products` entity commonly uses multi-words, so the `free-text` strategy will pick up new words eagerly. If you want to strictly restrict to a short list of keywords and synonyms, use the `keywords` only lookup strategy.
* Try first to merge the 3 `whatsapp` keywords into one to see if `whatsapp` only would be picked up instead of `whatsapp business`.
* `demo_services` only has two annotated utterance: "demo" and "demos". "demo" has been shown in a few annotated utterances for different intents: `demo_real_estate`, `demo_digital_assistant`, `demo_receipt_expense_management`, etc. The model is confused as it doesn't know to which class assigning utterances having `demo`. This requires more annotated utterances not conflicting with each other. A better strategy could be to have a single "demo" intent, and using an entity to extract the type of demo.
* Please switch to the new UX at your earliest convenience.

Hope this helps.
