### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by cybergirll** [wit-ai/wit#1932]
[**Do](https://github.com/HackerShackOfficial/AI-Smart-Mirror/tree/master/models
[wit_training_data.zip](https://github.com/wit-ai/wit/files/5322416/wit_training_data.zip)
) you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**
wit_training_zip does not parse

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** not my code, inspired by magic mirror project

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by ruoyipu** [comment]
Hi @akeysny! Looks like the ZIP is from 2016, so it's from a very old format that we don't support anymore
If you have access to a newer version that should work.

We don't usually recommend importing manually edited JSON since it can lead to issues -- but you can try exporting from an app right now and change the format of the old ZIP to match.
