### ISSUE TITLE
How should organizations access wit.ai?

### ISSUE THREAD

**Issue by ameola** [wit-ai/wit#1958]
Hi,

I'm a developer for an organization that would like to start utilizing wit.ai. However, we're a little unsure on how we should set this up considering wit.ai requires facebook to authenticate. Is there a way for us to create an organizational account through facebook that our org can use to authenticate? Most developers are hesitant to have their personal Facebook accounts associated with their organization and some developers don't have or want facebook accounts at all.

It would be really nice to have some guidelines around this added to the FAQ.

Thanks,
Aaron

**Comment by lycai-fb** [comment]
Thanks for bringing up this point. I'll discuss this with the team and get back to you.

**Comment by jtliao** [comment]
Hi @ameola, sorry for the delay here. Unfortunately it's not possible to create some kind of organizational account, since Facebook accounts need to be tied to a real identity. I understand the hesitance here, but it's the requirement to use the service going forward. After the accounts are made, you would need to manage the individuals associated with an app as contributors.
