### ISSUE TITLE
لفة \  -H 'التفويض: حامل CBFRZPZ2YEHUD26PPYP7BNWHXVJ4IWA2' \  "https://api.wit.ai/message؟v=20201127&q="

### ISSUE THREAD

**Issue by AlSufyaniT1** [wit-ai/wit#1968]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by kitchWWW** [comment]
Hello! This task isn't particularly actionable as it currently stands. If you would like to submit a bug or report feedback, please do so and fill out the form (specifying the behavior, possible bug, expected behavior, etc) and submit a new request. We'd be happy to help but unfortunately this issue as it currently stands isn't actionable.
