### ISSUE TITLE
Missing DateTime entity for Dutch language

### ISSUE THREAD

**Issue by MahyTim** [wit-ai/wit#198]
Hi,

we would really like to have a DateTime entity in Dutch or a clear documentation how we can extract date/times as such the default english entity does :)

**Comment by l5t** [comment]
Thanks for reaching out. We would love to get some help if you have time. We open sourced this part of the code here:https://duckling.wit.ai/. If you have time, don't hesitate to send us a Pull Request on the develop branch.

**Comment by Vincent-Noben** [comment]
The duckling link does not seem to have Dutch as a test option.

I want to use following datetime notations but have no clue how to add them. Currently Wit does not recognize any of them:
vandaag --> today
morgen --> tomorrow
maandag --> monday
dinsdag --> tuesday
woensdag --> wednesday
donderdag --> thursday
vrijdag --> Friday
zaterdag --> Saturday
zondag --> Sunday
weekend --> weekend (Gets recognized because same as EN)

Thanks

**Comment by eeziSL** [comment]
We're having exactly the same problem with the missing DateTime entity in Dutch. It does not recognise a single date or time value, which is pretty basic stuff for slot based chatbots for flight, hotel or restaurant bookings etc.

Anybody has been able to find some kind of solution for the DateTime entities with Dutch chatbots?

**Comment by blandinw** [comment]
There's something fishy here, we'll look at it today.

**Comment by patapizza** [comment]
`wit/datetime` is not available for Dutch, because it is not yet supported in Duckling.
To bring `wit/datetime` for Dutch, you can help by implementing it and making a pull request on https://github.com/wit-ai/duckling.

**Comment by patapizza** [comment]
`wit/datetime` is now available in Dutch!
