### ISSUE TITLE
Dummy Intents 

### ISSUE THREAD

**Issue by jurneek** [wit-ai/wit#2002]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question/Feature
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
With the new update of treating intents like first class citizens and requiring and intent to train apps that are only using entities will still work and function as normal users just won't be able to provide additional training without the dummy intent correct? 

Also if you could provide more insight for this change of requiring an intent to train and any other possible workarounds. 
**What is the expected behavior?**

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**

**Comment by wangsnowyin11** [comment]
Hey to answer your question:
- yes apps will keep working as before (this is actually enabled since the launch in May)
- dummy intents would work as a workaround in the UI
- the reason behind the change of making intents first-class citizens is that it's easier to think about, and in 99% of use cases NLP applications care first and foremost about intents
- the API POST /utterances supports optional intents to train without intents, but we didn't have the bandwidth to make intents optional in the UI
