### ISSUE TITLE
Wit datetime issue

### ISSUE THREAD

**Issue by mahavirtechnosip** [wit-ai/wit#203]
Hello,

I am facing an issue with datetime entity, i am looking for someway so that wit.ai identifies if datetime is for a particular day or after all dates following that day, let me explain both scenario with expressions.

1st : "fetch all football match after 5 days" : here i need some way wit tells me that start date(from) is 5 days from today and end date(to) is infinite, means fetch all that falls after 5 days.

2nd : "fetch all football match happening on 10th april" : here i am looking for some way that wit tells that fetch data only for 1 particular day. i.e. start date(from) will be 2016-04-10T00:00:00 and end date(to) will be 2016-04-10T23:59:59

or "show all football match happening tomorrow" : so here i am only interested about tomorrow's date, whereas "show all football match after 5 days" : here i am interested about all dates after 5 days.

Thanks :)

**Comment by mahavirtechnosip** [comment]
Suggestion, if wit.ai sees "on" world than it automatically generates "to" date.

**Comment by l5t** [comment]
Thanks for reporting. We open sourced our linguistic parser for datetime here: https://github.com/wit-ai/duckling. Fell free to have a look for next time.
In your example, we will need to tweak a rule to capture "after+duration" and return an interval and it will be done in the next couple of days.
Note that it works already the way you want with date instead of duration

- "fetch all football match after April 15th" returns:

`"type": "interval",
            "from": {
              "value": "2016-04-15T00:00:00.000-07:00",
              "grain": "day"
            },
`

- "fetch all football match happening on 10th april" returns

`"type": "value",
            "value": "2016-04-10T00:00:00.000-07:00",
            "grain": "day"
`
