### ISSUE TITLE
can't export date

### ISSUE THREAD

**Issue by sophiexr** [wit-ai/wit#2215]
hi, 

We've been trying for days to export the data from our (app 2841817995840539) and keep getting an error [object object ].
We click on Settings and then **export your data** (download .zip with your data), 
<img width="966" alt="export data issue" src="https://user-images.githubusercontent.com/48153186/136603887-0f0a0d00-2d52-4e54-85c2-dde773630543.png">
 and then a message [object object] appears next to the export button. (image attached).

Can you help?

Thanks

**Comment by ruoyipu** [comment]
Hi @sophiexr,

I believe due to the large number of utterances the export request is timing out.
I managed to get an export for you, to help unblock your work.
[CombinedTraits-2021-10-12-10-59-02.zip](https://github.com/wit-ai/wit/files/7332241/CombinedTraits-2021-10-12-10-59-02.zip)

You can also try the alternate way to export, via our Https APIS: https://wit.ai/docs/http/20210928/#get__export_link

Let me know if this helps or if you need anything else. Thank you!

**Comment by sophiexr** [comment]
@ruoyipu thank you very much for your help
