### ISSUE TITLE
Unknown error message showing when posting multiple intents

### ISSUE THREAD

**Issue by karnHarsh29** [wit-ai/wit#2245]
When i try to post multiple intents and train their utterances using API calls, i get `{ error: "Something went wrong. We've been notified", code: 'unknown' }` in my terminal.

Even after this error, the intent gets posted, maybe because the API call happens again, but it's utterances are not trained.

Also, I have noticed that if there is a two seconds gap in calling the post intent API, then this error does not show.

**Comment by yuzh174** [comment]
What is the app ID?

**Comment by karnHarsh29** [comment]
CSP2BKLRYHD73OH5WPBTYHKLRRD23GCX

**Comment by chessai** [comment]
@karnHarsh29 you posted your server access token, not your app id. Server access tokens can be used to act destructively on your app. I have edited your comment to redact the token. You may want to reset your server access token in the settings page of your app.

The app id is also on the settings page, please share that instead.

**Comment by karnHarsh29** [comment]
app id : 382153960317723

**Comment by yuzh174** [comment]
I see the utterances here https://wit.ai/apps/382153960317723/utterances. So that doesn't include the new utterances you wanted to add, I assume.

Could you share the API call and utterance you used to train the utterances? Don't include your server token in it. 
You can also try it again. We had an issue two weeks ago that the token was temporarily disabled. If that's the issue, it may work again.

**Comment by Barbog** [comment]
Closing due to no movement on the issue. Please re-open or file a new task should the issue be persisting.
