### ISSUE TITLE
/apps loading on mobile, but not on desktop

### ISSUE THREAD

**Issue by richgrov** [wit-ai/wit#2293]
Bug report: When attempting to access my apps (or any page for that matter,) the site sometimes refuses to load. It works on mobile devices fine, but not on Chrome Desktop (Ubunutu.)

[Here](https://drive.google.com/file/d/13NVok9MpuZjD5ltYDUW4aH5iMM2GoZ_g/view?usp=sharing) is a video demonstrating this behavior.

Notice how the favicon doesn't load. Most of the time, it *does* but beyond that, nothing else happens.

**Comment by jayyteee** [comment]
Hello @richgrov, I took a look and don't see any issues on our end around the time this was reported, and since it is working fine on your other device it most likely is your system or browser that is at fault. I would double check using a different browser, or if possible try to load the page on a different system. If you continue to see this issue on other devices then let us know and we can take another look.

**Comment by richgrov** [comment]
Fair enough. Thanks for the info!
