### ISSUE TITLE
500 Internal Server Error happening  on /message API 

### ISSUE THREAD

**Issue by nisreen93** [wit-ai/wit#2327]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug
**What is the current behavior?**
The mentioned API mostly gives us 500 exceptions.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
hit a word to /message
**What is the expected behavior?**
return 200 with understanding 
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
1920151674738030

**Comment by nishsinghal20** [comment]
Hey @nisreen93! Thank you for reporting this. We'll investigate and get back to you about this issue.

**Comment by gnovis** [comment]
I have the same issue. It is probably same as #2324 and #2315
My apps are usually working, but sometimes 500 error occurs for some utterance. I tried to remove one letter from the utterance which rises the error and Wit worked. Also if I trained the app with this utterance problem disappears (for trained utterance).
The error occurs unexpectedly over and over again.

**Comment by nisreen93** [comment]
Any Updates @nishsinghal20 regarding this issue?

**Comment by nisreen93** [comment]
Any updates here?

**Comment by nisreen93** [comment]
@nishsinghal20 ?

**Comment by nishsinghal20** [comment]
Hi @nisreen93! Apologies for not being able to get back to you sooner. I looked into the errors from your app for the last 30 days and some of these errors are intermittent server timeouts, some of them are due to the audio being too long - we enforce a max audio length of [20 seconds](https://wit.ai/docs/http/20210928/#post__speech_link). I saw few instances of an server side error that we'll be investigating, and we're constantly working towards making the service better support the requests so as to reduce the timeouts or throttling issues in near future.
