### ISSUE TITLE
Speech to text - problem

### ISSUE THREAD

**Issue by gchamorro1** [wit-ai/wit#2351]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?** BUG

**What is the current behavior?** It is not interpreting the audio

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
When sending an audio of less than 20 seconds, it is not interpreting what was spoken in the voice message.

**What is the expected behavior?**
Get the correct transcription of the voice message
**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID: 3315110748531064

**Comment by wangzhenict** [comment]
Hi @gchamorro1 , 
It's weird I didn't find error logs regarding 3315110748531064.
what's feature are you using? the normal audio -> witresponse (e.g. intents, entities, traits) ? or just a feature to convert speech to text?
Thanks,
Zhen

**Comment by SisikHBS** [comment]
facing the same issue, transcription accuracy is around 50%, it used to be around 95%

**Comment by gchamorro1** [comment]
Hi, in my case only the function to convert voice to text. 
I just send the voice message and use what it interprets.
As already said, accuracy is low and I get wrong answer. 
Can the accuracy rate be improved?

**Comment by bfavero** [comment]
I'm having the exact same problem doing Speech-to-text in Portuguese

**Comment by wangzhenict** [comment]
Hi @gchamorro1, @SisikHBS, @bfavero,
Got it. so this is accuracy issue, I'll work with related team on it. will keep you posted.

BTW, just want to double confirm, are you referring to api.wit.ai/speech functionality here?

**Comment by bfavero** [comment]
Yes, I'm using POST/Speech. 

Just to give you additional information, it was a sudden change that happened around Friday (11), maybe a few days before that. Since then, the API stopped working properly. There are no error messages, but it usually fails to transcribe big chunks of clear, easy-to-understand speech. It's not even that it transcribes it inaccurately, it just misses it.

To be sure it wasn't a problem with the audio files I was sending, I re-sent a 15s file that I had transcribed with Wit.ai last week. 

Here is last week's result:
0:01:28.20 -> 0:01:43:00 
Vamos falar de pandemia. O primeiro tema do Ocean é um tema muito grande. Então vamos começar sem muita demora. Então vejam só. Você deve estar sabendo né? **O geral que está acontecendo inclusive no vídeo de ontem trouxe lá a fala do Monark e basicamente fala né? Sobre**

Here is today's result (again, for the exact same file):
0:01:28.20 -> 0:01:43:00 
Vamos falar de pandemia. O primeiro tema do Ocean é um tema muito grande. Então vamos começar sem muita demora. Então vejam só.

As you can see, today the API simply didn't transcribe the part in bold. And this problem is happening with basically any files I send.

**Comment by rhenanbartels** [comment]
Hi folks! We are noticing the same issue as @bfavero +1.
The transcriptions are missing some text since a few days ago.

Our script sends a POST request to `/speech` using the same API version as before: `20200513`.

The App ids are:

- 1405971863131969
- 482412936218681
- 614470649974920
- 261358745932567

**Comment by bfavero** [comment]
@wangzhenict, are there any updates on this issue? I apologize for insisting, but my app has been broken for a week because of this.

**Comment by patapizza** [comment]
Alright, pushing a fix. Please note that `POST /speech` is meant for short inputs.

**Comment by gchamorro1** [comment]
@wangzhenict are there any updates on this issue? Thanks!

**Comment by bfavero** [comment]
It seems to be back to normal for me

**Comment by patapizza** [comment]
Should be back since 2/18 around 1pm PT.

**Comment by bfavero** [comment]
Hi @patapizza and @wangzhenict, sorry to bother you. But the exact same problem is happening again — the API return only a few words even in high-quality audio files that I had tested before. The problem started around two hours ago. Could you check this?
