### ISSUE TITLE
App stuck on ongoing 

### ISSUE THREAD

**Issue by aya-labiba** [wit-ai/wit#2389]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
question

**What is the current behavior?**
The app is stuck in training mode since yesterday, 9-3-2022 , its stuck on  "Training status: ongoing"

**What is the expected behavior?**
The app to finish training

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
App ID:  468849228311171

**Comment by NenaBas** [comment]
My app has been stuck on Training ongoing for more than an hour now, first time this happens to me, only adding to training one sentence at a time.

App ID: 228615856100539

PS: I found a past issue regarding this, saying to download the app and copy the data to a new one in order to workaround this issue, but it doesn't seem like a good solution everytime this happens.

**Comment by NenaBas** [comment]
Over 24 hours later and app is stick stuck on ongoing. This issue has delayed our work and we are closing in on a deadline. 
Please fix it

**Comment by aya-labiba** [comment]
Any updates? the app has been stuck on going for 5 days now. This is delaying our work.

**Comment by AlexisNichel** [comment]
Same problem here, plz helpme
APP ID: 1856185531061946

**Comment by hyde-wyvern** [comment]
Same problem here...
APP ID: 534242084738095

**Comment by doggeral** [comment]
These apps have been fixed
