### ISSUE TITLE
Merge context

### ISSUE THREAD

**Issue by anuradhasc** [wit-ai/wit#239]
I am trying to make bot remember the contact name till the end of their conversation. For example: User: Hi
Bot: Hi, May I know your name?
User: my name is xyz
Bot: How can I help u xyz?
User: Can you tell me what time it is?
Bot: It is "whatever date time" , xyz. 
Here in last answer bot is not taking xyz.  I tried adding contact name to the merge function. Still it is not remembered. Can someone please explain me how to do that with some short but detailed example?
Thanks

**Comment by molina-rodrigo** [comment]
i think there is a strong lack of documentation about how context works.
Can you please people provide more complex samples?

**Comment by StillOnMyWay** [comment]
How are you testing the bot? Meaning, what platform/programming language are you using?

Briefly, I'll explain Context vs Entities, as I've understood them. I'm using a modified wit-android-sdk to access the Wit server via HTTP.

**Context** : Context comprises anything important for the Wit server to use to answer an upcoming question. It can be generated by 

1. The preceding _merge(context,entities)_ method, where the user would have had to provide the context explicitly, which is basically saying "THIS IS IMPORTANT", making it a result of the merge function. This context can then be fed into an upcoming **sentence** or **action**, because it would have been created AS A RESULT of the merge function. This is as opposed to the merge function extracting the _**entities**_ automatically and using them in the following response.

2. The context can also be created by a user defined action, which may as a result of it's execution produce a context. This would be (in programming terms) the return value of the method. This means that when the function has completed execution, it will return to the Wit server a new response with whatever is defined in "Produces context" for that action, thereby saying "YOU'RE GOING TO NEED THIS" in order to complete an upcoming sentence.

**Entities**, on the other hand, are what are produced from the Wit server by their parsing of the entered sentence using the Duckling NLP and our defined rules. It creates a list of entities for the application then which it sends to the user mainly through the _merge_ function saying "HERE, YOU'RE PROBABLY GOING TO NEED THESE" (either now or later on). We can extract this list of entities from the response and decide if we need them or not in our programs.

Now, to actually answer your question, take a look at the [documentation on the converse api](https://wit.ai/docs/http/20160526#post--converse-link) here. You notice that their program requires the location as Brussels not only immediately after the question, but also later on as a return value of the fetch-forecast action, where it became part of the returned context.

Therefore in your example, you'd simply have to save the {"name":"xyz"} value from the list of entities after the bot asks for it(your name). You don't have to necessarily return this context from the merge method (in my experiments) for the bot to be able to respond immediately after, but if you want it to tell you the time with your name, you'd provide the context to the merge function which comes after the user asks "can you tell me the time".

I've been playing around with both the node.js, android sdk and curl HTTP requests, so I can only speak to those methods. I hope this "brief" explanation helps.

**Comment by diegolopezcdm** [comment]
how do remember the name to the end on the conversation?

**Comment by eekshi** [comment]
At present Iam unable to login with GitHub or Facebook for creating chat bot using wit.ai
