### ISSUE TITLE
*Urgent* Currently locked out of our company's account. 

### ISSUE THREAD

**Issue by itmanbrian** [wit-ai/wit#2463]
We have been developing on the Wit.AI platform for nearly 3 years and recently they switched over to Facebook-only for logins.

Somewhere along the line one of our developers switched the account and logic over but this account has been lost and now our mobile application (IOS) is calling with a token that we no longer have access/control of. 

We have tried to email wit.ai but have receieved no response. Can someone from the team please check your support requests at help@wit.ai and get back to us?

**Comment by yuzh174** [comment]
Hi @itmanbrian, what is your appID?

**Comment by itmanbrian** [comment]
We only have the API key, we don't have the APP ID or the specific name. I need to get in touch with someone from the WIT.AI support team ASAP. Please contact me at itmanbrian@gmail.com immediately so we can recover my companies account. We have been loyal supporters of this platform for years and look forward to working with you all more. Please get back to me at ITMANBRIAN@GMAIL.COM so we can investigate the issue at hand!

**Comment by yuzh174** [comment]
Hi @itmanbrian, we can definitely help with this process. 
Based on your description, you only have the API key, but not anything else related to the account. This makes the process more complex, since we do need to verify you are the actual owner of the mentioned wit.ai app. 

The good news is that there may be a much easier solution. Since you have the API Key (server token), you can export all the data from the account, and create a new account with that data with very simple steps: 
Steps:
1. Export all your data by https://wit.ai/docs/http/20220608/#get__export_link
2. Login to wit.ai with any FB account that you currently own, and create a new app with the data exported in step 1. 
3. Obtain the new token from the app and put that token into the client. 

Let us know if creating a new account would solve your problem. Otherwise we can move further to recover your account, however that will be much more complex due to security and legal concerns.

**Comment by itmanbrian** [comment]
Your trick worked :). Thank you so much!
