### ISSUE TITLE
Intent conflict

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2521]
Hi,

@doggeral 
We have 2 use cases iPhone 12 and iPhone 13 which have different responses. When we try to train the second question (iPhone 13), we are getting intent conflict with iPhone 12.
Can you please let us know how can we train these two as two different intents.

Thanks

**Comment by jayyteee** [comment]
Hi @anjaly 

First thing to try if the intents aren't always coming back as expected is to continue to train on more similar utterances - the more you can train on the better the result will be. Another option could be to use entities rather than intents, i.e. the utterance "iphone 13" would map to the 'phone' entitiy, with a resolved value of "iphone 13". Let me know if you continue to have problems.
