### ISSUE TITLE
Troubles while using context parameter in message endpoint

### ISSUE THREAD

**Issue by rheerdink** [wit-ai/wit#2556]
Since some days we experience problems while using the context parameter in the message endpoint. Before we received the information back from Wit, but now we receive a 500 for exactly the same request from our (not-changed) codebase. While using Postman to dig in, it looks like the handling of the context became became more strict?

Question is, has anything changed in the handling of the context parameter? Our appId is 790564278492320

This request works from Postman
https://api.wit.ai/message?q=maandag&context={%22reference_time%22:%222022-12-03T17:32:36+01:00%22}

The following request that worked before returns a 500 these days:
https://api.wit.ai/message?q=maandag&context=%7B%22reference_time%22%3A+%222022-11-03T18%3A19%3A29.845891%2B01%3A00%22%7D

**Comment by wangzhenict** [comment]
Hi @rheerdink ,
thanks for reporting this.
the issue should be due to a url parameter decoding change. '+' is not supported right now.
to quickly unblock you,
I suggest you replace the '+' with %20, or just remove the '+', this one should work for you:
https://api.wit.ai/message?q=maandag&context=%7B%22reference_time%22%3A%20%222022-11-03T18%3A19%3A29.845891%2B01%3A00%22%7D

meanwhile, I will try to bring it back to original status if you prefer to use '+'.

Thanks,

**Comment by rheerdink** [comment]
Thanks for the clarification @wangzhenict. 

We fixed it based on your input, however would be valuable in the future when these changes would be communicated and the libraries (pywit in this case) would be adjusted.
