### ISSUE TITLE
How to handle multiple "ingredients" within a single intent?

### ISSUE THREAD

**Issue by AnthonyPaulO** [wit-ai/wit#256]
"Please brew me a tea with 1 lump of sugar and a twist of lemon and a coffee with milk and 3 teaspoons of sugar"

Intent : Brew
Beverage: tea, coffee
Product: sugar, lemon, milk
Unit: lump, twist, teaspoon
wit/Quantity : 1, 3

The problem is that the response mixes everything together so you don't know what goes with the tea and what goes with the coffee.

**Comment by hactar** [comment]
I'd say the problem is that this isn't a single intent, these are two intents. You want to brew coffee AND brew tea, and wit can't do that yet (see #18). You could try attaching roles to the ingredients (first_beverage, second_beverage) and that might mitigate the problem, but with my experience with wit I'd strongly advise against this as wit will very likely get confused. And what if the user says "brew me a tea with 1 lump, a coffee with 3 lumps and a magic potion with 7 lumps": now you suddenly have 3 beverages involved, so you'd need extra roles for those too. It's just a mess.

I suggest you see these as individual intents and wait for #18 to be solved before proceeding.

**Comment by AnthonyPaulO** [comment]
If they will be parsed as multiple intents then I guess the question is, will the user have to spell out the intent each and every time? For example, will we have to say "Brew coffee and brew tea and brew xyz" or will "Brew coffee and tea and xyz" be sufficient? I guess we'll see when the time comes!

**Comment by l5t** [comment]
That could be achieved with composite entities (example here: https://wit.ai/l5t/EntitiesExample/intents/find_car). It is not yet supported in new apps with Stories but it's on our roadmap.

**Comment by okaris** [comment]
What is the status on this? Composite entities is a very important part of natural conversations.

**Comment by l5t** [comment]
We just reintroduced them: https://wit.ai/blog/2017/02/24/reintroducing-composite-entities
