### ISSUE TITLE
Question - How long does a bot session last before wit invalidates or resets it?

### ISSUE THREAD

**Issue by adhilmunna** [wit-ai/wit#2598]
Could you elaborate about the session expiry mechanism and timings within wit. 
Also, does wit invalidate/reset all sessions when a new deployment to runtime is made?

**Comment by yuzh174** [comment]
The session expiration time is 30 days. 
If you deploy a new graph to prod, it won't reset your existing sessions, but there is a risk that your existing sessions may not work due to graph connection change. 

The more proper way to do it in prod is to use the versioning in wit. https://wit.ai/docs/recipes#version-your-app . This way  the new prod graph won't affect existing sessions.

**Comment by adhilmunna** [comment]
thanks @yuzh174
