### ISSUE TITLE
How do you indicate in the new Bot Engine that an entity is being removed from the context?

### ISSUE THREAD

**Issue by mgfcm** [wit-ai/wit#261]
My logic relied on the bot not doing a particular action until a particular entity was removed from the context.

**Comment by ar7hur** [comment]
In order to simplify the Stories UI, we've removed this feature. The recommended solution is to add an entity `my-entity-removed` on your side when your entity is removed (and use this one in your story).

It's not perfect, but we will probably add a more expressive way to rely on entities in Stories soon (things like == value, <, boolean logic, etc.). Absence of an entity will be covered by that.

**Comment by mgfcm** [comment]
That's unfortunate. Thanks for the reply though.

**Comment by kulpreet** [comment]
@ar7hur The slot filling example on the Recipes page uses logical operator to confirm the context-keys are set in the context. Is that supported yet?
