### ISSUE TITLE
 There was an error validating the utterance.

### ISSUE THREAD

**Issue by vishwa1st** [wit-ai/wit#2638]
![Screenshot from 2023-06-16 12-31-42](https://github.com/wit-ai/wit/assets/136789759/7c9037fb-988a-4165-9163-a00f997e0319)

Why is this happening? need a fix ASAP kiyala

**Comment by vishwa1st** [comment]
Why is this happening? need a fix ASAP

**Comment by nishsinghal20** [comment]
Hi @vishwa1st! Can you please share the Wit app ID and the time range when you noticed this issue? Is it still happening?

**Comment by vishwa1st** [comment]
Hi @nishsinghal20  My app ID is **2698477293496227**.  this error occurring from yesterday. still not working. we need to fix this ASAP

**Comment by vishwa1st** [comment]
Hi @nishsinghal20  My app ID is 2698477293496227. can you please look into this

**Comment by nishsinghal20** [comment]
Hi @vishwa1st! Apologies for the delay in getting back to you. I looked at our logs, and it seems that we had a few requests that errored out due to an app config failure around June 13th. I'll take a deeper look at what caused this issue on our end. There are few other failed requests which are user error as the message provided to the GET /message was too long.

The app looks healthy to me for the last couple of days. Let me know if you're still seeing any issues.
