### ISSUE TITLE
Cannot migrate my App from my Facebook account!

### ISSUE THREAD

**Issue by PL-OVA** [wit-ai/wit#2657]
Hi!

Since the Wit.ai migration to Meta account, I cannot access the App (440413651410516) I have created with my Facebook account at [pllapointe@ova.ai](mailto:pllapointe@ova.ai). I already have a Meta account and I was assuming that it was somewhat linked to my Facebook one, but I do not get prompted to migrate my Wit.ai app when I login, so I am stuck there and cannot access the app.

Any help would be greatly appreciated.

**Comment by ChrisyShine** [comment]
@PL-OVA 
When you login wit.ai, have you ever seen the checkbox like this?
![wit.ai apps migration confirmation checkbox](https://miro.medium.com/v2/resize:fit:720/format:webp/1*Px1VO_Ki9nETqAePQC0Zcg.png)
Or there is no checkbox during the login process?
If there is no checkbox, it means that your Meta account is not linked to your FB account. The old wit apps won't be migrated without the Meta x FB account linking. 

If currently your Meta account is not linked to your FB account, there are several options to recover the wit apps.
Option 1: You can create a new Meta account by continue with FB. In this way, you will have a new Meta account and you can login wit.ai with the new Meta account. Your old wit apps will be migrated if you keep the wit app migration checkbox checked.
Option 2: You already have a Meta account, you have login wit.ai with that Meta account. If the new wit account is still empty, delete the new wit account first. And wait for up to 30 mins for the deletion fully completed. And go to Meta account center, link your Meta account with your FB account. After the account linking, go to wit.ai and login with your Meta account again. Since you deleted the wit account, you will be navigated through the wit.ai login process again and this time, make sure that you see the wit apps migration checkbox and keep the checkbox checked.

You can try these 2 options first, and if still not working, I will help you from my end and I may need more information from you to recover your wit apps.

**Comment by PL-OVA** [comment]
Hello Chrisy! No, I did not see that checkbox. In fact, I did not see that screen either, although I expected it to show up at some point but it never did. I will try option 2 and let you know. Thanks!

**Comment by PL-OVA** [comment]
Update. After having tried Option 2, I saw the migration screen with the checkbox, however when I click the "Continue as" button, it bring me back to the Wit.ai page and displays an error. See the attached screenshot. 
<img width="1321" alt="Screenshot 2023-08-04 at 3 46 38 PM" src="https://github.com/wit-ai/wit/assets/141368203/6ac95ace-7569-4330-8733-3d30498cd551">

**Comment by ChrisyShine** [comment]
@PL-OVA The login error is because the wit account deletion is not fully completed. You may need to wait for more time.

**Comment by PL-OVA** [comment]
@ChrisyShine It worked Chrisy! Thank you very much for your help!
