### ISSUE TITLE
Missing Apps Display on Website

### ISSUE THREAD

**Issue by taximeter** [wit-ai/wit#2667]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
in current website wit.ai by my account email "chatme.inet@gmail.com" can display app created during 2023-03-01 to 2023-06-30 but in my account have app created since 2020-09-03 and all my app will create by token wit app "2740615422925018" 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
login to my account and find apps

**What is the expected behavior?**
see all my apps in my account

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
2740615422925018

**Comment by rokeyge** [comment]
Hi @taximeter,

When you login wit.ai, have you ever seen the checkbox like this?
![image](https://github.com/wit-ai/wit/assets/119081/e09e1fe2-b6c0-427e-8a68-76cd0319c11c)
wit.ai apps migration confirmation checkbox

Or there is no checkbox during the login process?
If there is no checkbox, it means that your Meta account is not linked to your FB account. The old wit apps won't be migrated without the Meta x FB account linking.

If currently your Meta account is not linked to your FB account, there are several options to recover the wit apps.
Option 1: You can create a new Meta account by continue with FB. In this way, you will have a new Meta account and you can login wit.ai with the new Meta account. Your old wit apps will be migrated if you keep the wit app migration checkbox checked.
Option 2: You already have a Meta account, you have login wit.ai with that Meta account. If the new wit account is still empty, delete the new wit account first. And wait for up to 30 mins for the deletion fully completed. And go to Meta account center, link your Meta account with your FB account. After the account linking, go to wit.ai and login with your Meta account again. Since you deleted the wit account, you will be navigated through the wit.ai login process again and this time, make sure that you see the wit apps migration checkbox and keep the checkbox checked.

You can try these 2 options first, and if still not working, I will help you from my end and I may need more information from you to recover your wit apps.

**Comment by taximeter** [comment]
@rokeyge I can't try 2 option because in now my meta account have wit apps I can't to delete account and Facebook account is same meta account 
I hope you help me recover my wit apps, I can send more information for you need

**Comment by rokeyge** [comment]
Could you please share your new wit.ai user id? It will be on the top right corner of the page after you log in.

**Comment by taximeter** [comment]
![image](https://github.com/wit-ai/wit/assets/16710125/fa2d7023-971f-4747-a8cc-5cf24c82f127)

username : witty_hacker_W5KETCQ

**Comment by rokeyge** [comment]
Thanks for the information. We have migrated the apps for you to the new account.

**Comment by taximeter** [comment]
Thanks @rokeyge
