### ISSUE TITLE
Some apps are not displaying within my old created apps

### ISSUE THREAD

**Issue by JumanaNajdawi** [wit-ai/wit#2668]
Hi dears,

--> Umniah_UM_Chatbot_Release_UM_App_AR
app ID (1920151674738030)
--> Umniah_UM_Chatbot_Release_UM_App_EN

These two apps are not displaying with the other previously created apps, whether in the "My Apps" or "Shared Apps" lists.

Unfortunately, I have the first app ID only, I don't have the second app ID.

Please your support to show these apps along with the other apps I have.

Regards,

**Comment by rokeyge** [comment]
When you login wit.ai, have you ever seen the checkbox like this?
![image](https://github.com/wit-ai/wit/assets/119081/f6b047f5-ec8c-4a7b-833d-31819e5b4fbb)

wit.ai apps migration confirmation checkbox

Or there is no checkbox during the login process?
If there is no checkbox, it means that your Meta account is not linked to your FB account. The old wit apps won't be migrated without the Meta x FB account linking.

If currently your Meta account is not linked to your FB account, there are several options to recover the wit apps.
Option 1: You can create a new Meta account by continue with FB. In this way, you will have a new Meta account and you can login wit.ai with the new Meta account. Your old wit apps will be migrated if you keep the wit app migration checkbox checked.
Option 2: You already have a Meta account, you have login wit.ai with that Meta account. If the new wit account is still empty, delete the new wit account first. And wait for up to 30 mins for the deletion fully completed. And go to Meta account center, link your Meta account with your FB account. After the account linking, go to wit.ai and login with your Meta account again. Since you deleted the wit account, you will be navigated through the wit.ai login process again and this time, make sure that you see the wit apps migration checkbox and keep the checkbox checked.

You can try these 2 options first, and if still not working, I will help you from my end and I may need more information from you to recover your wit apps.

**Comment by rokeyge** [comment]
Please let us know if the problem persists.

**Comment by JumanaNajdawi** [comment]
Hi dear,
Thank you for your support, 
but the issue wasn't solved.
Can you check it from your side, these apps are connected with production chatbots, but we can't access them.

Thanks,

**Comment by ChrisyShine** [comment]
@JumanaNajdawi Can you share your new wit username? You can find the username from the top right corner of the page after login with Meta account.

**Comment by JumanaNajdawi** [comment]
Hi Chrisy,
Thank you for your quick reply,
HYG
User Name: **ahmadomar**

**Comment by ChrisyShine** [comment]
@JumanaNajdawi 
I've migrated the apps for you. Now you should be able to see these 2 apps now. Besides these 2 apps, there were also other 100+ apps migrated.

**Comment by JumanaNajdawi** [comment]
Thank you so much 
Appreciate your support
