### ISSUE TITLE
Apps missing after migrating to meta account

### ISSUE THREAD

**Issue by morning-calm** [wit-ai/wit#2669]
Our wit.ai account has been migrated from a Facebook account to a Meta account using the same Facebook email address.

We noticed that some wit.ai apps in the existing Facebook account weren't present in the meta account after migration. Here are the details of the missing app IDs:

511210084349381
949539342164783

The new user name requiring ownership of these apps is davidsobell_LDYHR2A

Thanks for helping

**Comment by ChrisyShine** [comment]
@morning-calm Most probably, when you logged in with the Meta account for the first time, you unchecked the checkbox for data migration. The wit apps were still on the old wit account.
Since it is proved that you own the old data, I've migrated the old apps to your new account.
Now if you login with Meta account, you will see your account with the username davidsobell (The same username as before). And you should be able to see your wit apps: 511210084349381 and 949539342164783.

**Comment by JumanaNajdawi** [comment]
Hi @ChrisyShine,
I'm having the same issue, 
--> Umniah_UM_Chatbot_Release_UM_App_AR
app ID (1920151674738030)
--> Umniah_UM_Chatbot_Release_UM_App_EN

These two apps are not displaying with the other previously created apps, whether in the "My Apps" or "Shared Apps" lists.

Unfortunately, I have the first app ID only, I don't have the second app ID.

Please your support to show these apps along with the other apps I have or any hidden apps that I didn't mention.

Regards,

**Comment by ChrisyShine** [comment]
@JumanaNajdawi You can reopen the issue https://github.com/wit-ai/wit/issues/2668 to follow up for your problem. I've replied to your in 2668.
