### ISSUE TITLE
Add location to HTTP API's context

### ISSUE THREAD

**Issue by tdeckers** [wit-ai/wit#27]
Suggestion to add 'location' to the context object in the HTTP API.  This will allow me to place recording devices in different places and say things like 'Turn on light'.  This should then infer the location from the recording device's location.

**Comment by l5t** [comment]
Ok, let's be honest here... It was on the roadmap 2y ago... With the release of Bot Engine we will work on it soon and I hope it won't take 2y this time ;-)

**Comment by blandinw** [comment]
We're doing a cleanup :-)

@tdeckers @Seraf thank you again for your feedback.
I thought this issue was about using the user location to help resolve locations (.e.g "meet me on University St.", is it Uni St. in Palo Alto or Berkeley? etc). However, this is not what this is about, right?

I'm not sure I understand this need exactly. As ar7hur said, if you know the location of the device, you should just use it in your client-side code, why do you need Wit to return it?

Can you elaborate on the actual need? I'll close in the meantime, but please feel free to reopen with more info.
