### ISSUE TITLE
Inconsistent response from wit.ai

### ISSUE THREAD

**Issue by anjaly** [wit-ai/wit#2729]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
We had trained a question 'money' and if we input 'the money', till yesterday it was returning 'money' intent with .9 confidence. But now if we try the same question it is returning no intent. We haven't done any training on this app for few days.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Try the question 'the money' in Understanding tab.

**What is the expected behavior?**
Should return the money intent

**If applicable, what is the App ID where you are experiencing this issue? If you do not provide this, we cannot help.**
376879450680207

**Comment by nishsinghal20** [comment]
Hey @anjaly! Seems that your training data only contained "money", hence when you query using "the money", it doesn't return any intents. If you query using just "money", you'll get the expected results. Please train your app with more data and variations so that the model can get better at predicting the correct intent.

**Comment by anjaly** [comment]
@nishsinghal20 But this was working earlier. 
Also need one more clarification, won't the nlp identifies the intent with the matching keyword or will it identify only with the exact sentence.
