### ISSUE TITLE
Bookmark disappeared again - and now I CAN'T write it back, wit.ai says I already have a bookmark with this name

### ISSUE THREAD

**Issue by misysdclabs** [wit-ai/wit#284]
Hi Guys,

Today I find again one of my wit.ai apps w hit a missing bookmark.
(connected issue: #281)

<img width="141" alt="screen shot 2016-08-04 at 10 59 33" src="https://cloud.githubusercontent.com/assets/14309287/17396397/858ce7f4-5a33-11e6-857b-f705761e72aa.png">

But I have something new. When I try to fix it, to write back my 'pay' bookmark, I got a message saying I already have a 'pay' bookmark, so I can't define it again.

<img width="353" alt="screen shot 2016-08-04 at 10 59 56" src="https://cloud.githubusercontent.com/assets/14309287/17396607/6be38bf4-5a34-11e6-9902-f73a17fff2cb.png">

I checked over all my stories. I exported the app to json. I do NOT have any 'pay' bookmark. It is really disappointing :(

@l5t , could you please help me with this? What did I wrong?

**Comment by jhoelzl** [comment]
Same issue: #257

**Comment by milindaj** [comment]
Even I am facing the same issue.

Wit team - any suggestions? and if you know this is a real problem then any idea when we can expect the fix for this? I really appreciate the work that you have done on wit but I must say that there is some scope to improve the wit story and actions interface. Many times I can not save the story or my changes disappear on next login

**Comment by magnusburton** [comment]
Happens to me as well. I tried creating a new bookmark with the same name and Wit told me that bookmark name was already in use. I think it happens when you create/remove branches and then save

**Comment by magnusburton** [comment]
Started happening again yesterday but worked fine for a long while!

**Comment by Mariskavh** [comment]
Today this happened to me as well. Wit remembered that there were jumps, but the name of the specific bookmark had disappeared from those jumps, as were the bookmarks itself.

**Comment by patapizza** [comment]
Sorry for the delay!

@magnusburton @Mariskavh What is your app name?

**Comment by Mariskavh** [comment]
Hello @patapizza , 

The url is: https://wit.ai/marisvh/RequestResources/stories. But since last week I have created a new (similar) app which has not caused any issues so far. Thank you anyways :)

**Comment by magnusburton** [comment]
@patapizza 

I managed to recreate every single bookmark on my app and has not attempted to enter the console again since that time. It seems like it occurs only if you enter the console and since I don't need to make any changes to my stories I resist from logging in. https://wit.ai/magnusburton/Lisa_SV

**Comment by zetos** [comment]
@magnusburton thanks for the tip. It worked for me.

**Comment by patapizza** [comment]
Closing in favor of #257 and #281
