### ISSUE TITLE
Stories first action conflict

### ISSUE THREAD

**Issue by cisnky** [wit-ai/wit#321]
Can somebody explain why the mergeIntentOld conflicts with mergeIntentTeam?

https://wit.ai/cisnky/fb_weather/stories

Is it because both stories use wit/contact?

Should an app only have one story that deals with the entities?

Has anyone had much luck with apps that have multiple stories.

**Comment by l5t** [comment]
Hello, it's because you will need an trait entity (your "intent" entity is keyword currently). Only trait entities have their value influence the prediction. For non-trait entities, the value is ignored with regards to action prediction. More info here: https://wit.ai/docs/recipes#extract-and-store-information-from-user-messages

**Comment by cisnky** [comment]
@l5t Thank you so much.
