### ISSUE TITLE
Renaming intents

### ISSUE THREAD

**Issue by jholt1** [wit-ai/wit#377]
Renaming intents has broken the intents. Expressions are still linked to old intent names, which means all learnings have seemingly been lost. Is there a fix for this, thanks? (Quite urgent as in production)

**Comment by blandinw** [comment]
Renaming an intent should not break training, etc. It may impact your app if your code depended on it. For mass reassignment, you can also use the API (https://wit.ai/docs/http/latest) to upload data for a given intent.
If this is still an issue, please reopen with your App ID for us to investigate.

**Comment by jholt1** [comment]
Seriously 23 days...

**Comment by blandinw** [comment]
This is frustrating for us too, we're trying to improve the process.
GitHub was not actively monitored until yesterday: https://www.facebook.com/groups/withackers/permalink/230015834071338/

Let us know if we can help further on this issue.

**Comment by jholt1** [comment]
Here is a test app - 58c0a846-dc5d-491e-a439-239f2cd851a5

Renaming the trait from `hello` to `hi`still keeps it as `hello`

<img width="987" alt="screen shot 2017-03-09 at 00 59 02" src="https://cloud.githubusercontent.com/assets/7101754/23731162/d2a442e6-0463-11e7-9d81-4df80fe06633.png">

**Comment by blandinw** [comment]
@jholt1 You're right, we did not automatically update validated samples when an entity value changed. This is now fixed in production. Updating a whole dataset can be an expensive operation, so this happens in the background and shows a (hopefully) helpful error message.

![image](https://cloud.githubusercontent.com/assets/413070/23777615/cd0283d4-04ea-11e7-9f3b-706f193a55da.png)

Thanks for your feedback, let us know if we can help further!

**Comment by jholt1** [comment]
Thanks for fixing it @blandinw 

Just a question about what you just said. Shouldn't the relationship between the entity and the expression be a unique id rather than the value? (not that I know how your system works 😀)

**Comment by blandinw** [comment]
@jholt1 Yes it should. As a startup, we had to strike a balance between moving fast and doing things perfectly. Having meaningful names instead of IDs helps in external systems (away from the database) and a good chunk of our time was spent improving/debugging stand-alone ML algorithms. Also, we ended up creating the "intent, entities, values" model, but it wasn't clear then that this would stick or be what we wanted to solve (other services walked in our footsteps later). Iteration speed was important.

Now, obviously today we don't have the same constraints and we should really be using IDs. That's one of the many things we're fixing as we move to the facebook.com stack (cf. https://wit.ai/blog/2017/02/10/wit-community-update).
