### ISSUE TITLE
Case sensitive entity values - how?

### ISSUE THREAD

**Issue by nikbora** [wit-ai/wit#399]
If I have a custom entity `team_name` which I use for querying our database of teams at some point in the conversation, then how do I allow the user to input `teamX`, `teamx`, `TeamX` as values and for all to be different entities?

At the moment whichever of those values is trained on first will be the one picked up in all variations of case afterwards.

So far I tried:

- Playing with the type of entity (free text + keyword, keyword only, trait only)
- Attempting to train with all versions of case. This still results in a keyword or trait not created for second variation.

Is this a limitation in wit.ai, or should I be taking a different approach (such as using wit/body_message as an entity for example?)

**Comment by l5t** [comment]
Thanks for asking. You have a concept of value for entity and synonyms or expressions for this value. In your case you should not need to add synonyms since keyword entity supports case. I just validated one expression with entity value teamX and see below it can detect TeamX

![image](https://cloud.githubusercontent.com/assets/6992759/23785115/d7f6e110-051a-11e7-92a8-048016813ee5.png)
