### ISSUE TITLE
500 Errors from inbox

### ISSUE THREAD

**Issue by individual11** [wit-ai/wit#481]
*bug*

Seeing a 500 error when I try to verify stuff in the inbox

Go to inbox, click on _Validate_

It should move on to the next one, but instead it throws a 500 and the message pops back up on top.

**Comment by domsammut** [comment]
Hey @blandinw,

I'm receiving these errors on a number of items in my Inbox. I'm unable to validate or delete (would prefer to validate). For items I see come through in the first hour I'm able to validate / delete but stuff from past that point I am unable to delete / validate. Just wondering if there's been any further update on this / what causes it so I can try and mitigate from my end.

Cheers
Dom

**Comment by blandinw** [comment]
@domsammut There's a known issue with subentities. Expect a fix soon.

**Comment by blandinw** [comment]
Issue mitigated, proper fix coming on Monday

**Comment by domsammut** [comment]
@blandinw Thanks for the update and appreciate the temp fix 👍

**Comment by domsammut** [comment]
Hey @blandinw, not sure what's happened, but the mitigation that was put in place no-longer appears to be working (first time I noticed it to have died was around [7am UTC+11](http://everytimezone.com/#2017-11-7,-960,cn3)). 

Tried and tested a number of times since that point with no luck. Is there something on my end that causes this to occur?

Cheers
Dom

**Comment by stopachka** [comment]
fixed once more! let us know if anything 

cc @blandinw
