### ISSUE TITLE
Flow-based bot don't return values.

### ISSUE THREAD

**Issue by VitorAndrade20** [wit-ai/wit#533]
I hope I'm not being too noob, but on the recipe exemples, on the when you create the context key "result" my bot doesn't return the required value of 'sport', just "{results}" instead.

This is my App ID: 58febf9e-183a-4cf7-a00a-95e224debb49

Looking Foward for your answer, I'm going crazy here.

P.S.: Please, forgive my English. I'm not a native speaker.

**Comment by patapizza** [comment]
Hi,

The bot looks into the context and in the found entities. The story you wrote says that `compute-result` adds `result` in the context, after which the bots says "Ok, here are the result {result}". You are responsible for making sure that `compute-result` sets a key `result` in the context.
When testing in the console, the `result` value is not available, since the client code is not run, hence showing `{results}`.

Hope this helps
