### ISSUE TITLE
Enhancement: Strict enumeration for entities

### ISSUE THREAD

**Issue by drewcrawford** [wit-ai/wit#64]
There are times when the only valid choice for an entity is something on a list.

> Send an email to **Jim**
> Show me the P&L on the **Hathaway** account
> Show me the open bugs for the **UI** component

In all of these cases, the user is asking me to identify a particular record from an existing set of data that I have.
1.  The user asks me to send an e-mail to Jim, which assumes that I have Jim's email address.  Not all names are acceptable inputs for this intent; the only names that are acceptable are names for which I can find an email address, e.g. from the address book or something.
2.  The user asks me to pull up data on a particular account.  You can't just pass me any old string, it has to be one of the accounts my application knows about.
3.  The user asks me to show the open bugs for a component.  You can't just make a guess for the component_name entity, it has to be in a list of software components I already know about.

So really what I'd like is some way to pass along with the input text "As far as the account goes, you have to pick from 1 of these 10 things.  I don't accept any arbitrary string."

**Comment by conradev** [comment]
> What you refer to is what we call "dynamic enums". That's almost ready to be released for the text API.

Any update on this for the text API?

**Comment by blandinw** [comment]
Please see the `entities` field in the `context` object when you call the API: https://wit.ai/docs/http/20160330#context-link

@conradev can you quickly tell us about your use case to make sure we're not missing anything?

**Comment by conradev** [comment]
@blandinw That looks like exactly what I would need – thanks! This ticket can probable be closed, then.

**Comment by conradev** [comment]
@blandinw The user has a collection of "widgets". Each widget has a name. I want the user to select a widget with their voice.

The problem I ran into is that with the "keyword" setting on the entity, if the speech to text returns a result that doesn't exactly match a value (sent dynamically with the context), then the result has no entity instead of picking the best matching one.

**Comment by blandinw** [comment]
@conradev We still do some light fuzzy matching on the entities you send, but you are right that we don't return the "least bad option". What if the user says something radically different from what you're expecting? You would have to define some distance threshold, that will be specific to your app.

We don't return the "least bad option" because you may have a bunch of different entities defined in your Wit app, and always returning all entities with a confidence/distance score would get unwieldy and confusing pretty fast.

Are you suggesting that we always return all "dynamic entities" (sent via context) with some kind of distance/confidence score?

In the meantime, as a workaround, I would recommend that you run an edit distance algorithm (e.g. Levenshtein distance) on the user sentence on your side and pick the threshold that best suits your needs.

**Comment by conradev** [comment]
@blandinw That totally makes sense, I didn't consider my feature request in the scope of the Wit ecosystem. Scoring all of the dynamic entities, or just returning the one with the highest score would indeed achieve what I am looking for.

For now, I can definitely run an edit distance algorithm for non exact matches with a custom defined threshold. Is Wit's speech to text conversion affected at all by the possible entities? If not, I might as well just use Google's Speech API for this

**Comment by blandinw** [comment]
Wit's speech rec is not affected by dynamic entities, so Google should work as well

**Comment by greenroutes** [comment]
@blandinw Do you guys have any roadmap for the release of the above mentioned dynamic entities with scores? Thank you.
