### ISSUE TITLE
Integrate Wit.ai with Salesforce without any Middleware

### ISSUE THREAD

**Issue by PN9** [wit-ai/wit#659]
Can we integrate Wit.ai framework and Salesforce backend directly, without using any Middleware services?
Can we hit the Salesforce URL's directly from the Chatbot? If so, please let me know the steps.

**Comment by yegeniy** [comment]
Can't speak officially, but in order to do that, wit.ai would need to provide a WebHook of some kind, which it does not as far as I can tell.

Alternatively, you can try reaching out to some tools developers, like those of troops.ai, which provide Salesforce integrations into a chatbot, but I don't think they are leveraging wit.ai.

**Comment by blandinw** [comment]
I'm not familiar with the Salesforce backend, so you'll have to provide more details.
We don't provide webhooks integration at the moment, but we may in the future if there's a strong enough demand.

**Comment by blandinw** [comment]
Closing until we get more information.
