### ISSUE TITLE
The message does not correspond to the intent

### ISSUE THREAD

**Issue by BenMoreton** [wit-ai/wit#680]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
I Have a story that says "Hi" when someone says "Hello"
I Have an other story that says a specific message when someone ask us to be published on our facebook page
Sometimes, it responds with "Hi", even if "AppearsOnFacebook" intent is detected

![capture d ecran 2017-07-25 a 08 13 10-2](https://user-images.githubusercontent.com/11722993/28558410-1d419bda-7112-11e7-9f1c-c85b644af1a6.png)

![capture d ecran 2017-07-25 a 08 04 52](https://user-images.githubusercontent.com/11722993/28558418-2565c93a-7112-11e7-9898-7c1eedca12ac.png)

![capture d ecran 2017-07-25 a 08 05 06](https://user-images.githubusercontent.com/11722993/28558425-27ad4664-7112-11e7-9380-003700a2bde9.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
"Hi, can you share on your page plz?" message got a 99% of confidence for "AppearsOnFacebook" but returns the "_Hello" intent / story message

**What is the expected behavior?**
Replying with the "AppearsOnFacebook" story message

**What is the App ID where you are experiencing this issue (if applicable)?**
5947e871-341b-4303-aecb-0724f6ccc7c5
This also occurs on the french app:
593f9df5-67d7-4bea-adec-709425a2a8a5

**Comment by blandinw** [comment]
Did your `Help-get80.AppearsOnFacebook` action properly populate the context with the "text" key?

**Comment by blandinw** [comment]
Nevermind, I looked at your app quickly and it does not even get to `Help-get80.AppearsOnFacebook`. The issue is that your `80.AppearsOnFacebook` story needs 3 entities to be extracted to be likely chosen.

The sentence "Hi" does not contain the 3 entities that you declared at the beginning of the story.
The sentence "Can you put my child on your facebook page please ?" has the 3 entities, and the `80.AppearsOnFacebook` is correctly chosen.

This is expected behavior. If Stories does not fit your needs, we recommend that you use the `GET /message` API to extract entities and write some client-side logic to dictate exactly the behavior you want.

**Comment by BenMoreton** [comment]
Thanks your time, I'll try the API to look deeper into it.

The thing that I totally don't understand, is why there is an inconsistency between the intent and the displayed message.

On this example - like you said in your response - it's the correct behaviour, the 80.AppearsOnFacebook story is chosen:

<img width="704" alt="capture d ecran 2017-07-26 a 10 55 34" src="https://user-images.githubusercontent.com/11722993/28612977-45a4a4ac-71f1-11e7-9591-cbbf59648a30.png">

However, if the same sentence starts by "hi", the result is the "_Hello" Story message, BUT it detects 80.AppearsOnFacebook.

<img width="728" alt="capture d ecran 2017-07-26 a 10 55 09" src="https://user-images.githubusercontent.com/11722993/28613032-720a032a-71f1-11e7-907b-ebb9245a3c10.png">

So that's this inconsistency that I don't understand!

**Comment by blandinw** [comment]
Well, when you start with "Hi", the entities extracted are not the same and the model decides to go with your "_Hello" story instead, because it has learnt that having the entities `hello` and `wit/greetings = true` are strong indicator that this is for the "_Hello" story. See below for a visual-ish explanation.

Now unfortunately, Stories is not learning the behavior you had in mind. To be pragmatic and make progress, I would recommend using the GET /message (Understanding) API, so that you can just get the entities and code whatever behavior you had in mind using client-side logic.

**Understanding**

![image](https://user-images.githubusercontent.com/413070/28635560-eacce2f2-71ef-11e7-95f9-7b770e1daffc.png)

![image](https://user-images.githubusercontent.com/413070/28635557-e87344b0-71ef-11e7-8df1-368d5a36a992.png)

** Stories **

![image](https://user-images.githubusercontent.com/413070/28635602-0904b54c-71f0-11e7-8c67-3b158a61defb.png)

![image](https://user-images.githubusercontent.com/413070/28635604-0a737904-71f0-11e7-9a7c-f7736e922c6b.png)
