### ISSUE TITLE
`GET` /inst/{user}/{app} is returning 500 error

### ISSUE THREAD

**Issue by paolopaolopaolo** [wit-ai/wit#727]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
The API call returns a 500 error.
![image](https://user-images.githubusercontent.com/5480842/29470146-1a14ae38-8400-11e7-8400-731984a2faf4.png)

Then nothing appears on the page.
![image](https://user-images.githubusercontent.com/5480842/29470250-7a509dca-8400-11e7-8239-67ac3749461b.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Log in to account with access to `dpaolomercado/SFChatbot`
* Click on that app

**What is the expected behavior?**
* Navigate to the app "Understanding" page

**What is the App ID where you are experiencing this issue (if applicable)?**
`dpaolomercado/SFChatbot`

**Comment by stopachka** [comment]
Hey @paolopaolopaolo, should be back to normal now :) 

-- more detail:

You caught an interesting bug!

Because you were also a contributor to a different app, also named SFChatbot, this was causing some issues in Wit. 

I temporarily changed the name of leemcdole/SFChatbot to leemcdole/SFChatbotDiff. 

We'll make a permanent fix in the roadmap, that accounts for this
