### ISSUE TITLE
App hangs in training mode

### ISSUE THREAD

**Issue by mmsat** [wit-ai/wit#740]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
bug

**What is the current behavior?**
Bot is in "training mode" for hours 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
We have added a custom trait entity and added around 250 values to it. We then posted the same amount of /samples - one for each value. App is in Training mode since and does not seem to recover.
 If using the "Understanding" function in the GUI some expressions deliver the correct entity but not via API, others don't deliver anything. If we manually add expressions this does not seem to get recognized.

**What is the expected behavior?**
Have a working application afterwards.

**What is the App ID where you are experiencing this issue (if applicable)?**
599c4a26-41c1-4d90-9de1-bda26c02fcf8

**Comment by hweiler** [comment]
I've had the same issue as well. We have had a higher volume of site visitors using our app over the last few days, so we're constantly training the app. I stopped yesterday afternoon since none of my changes were working while it was training.

I came back to the app this morning and it's still in on-going training mode even after being left alone for a night.

**Comment by mmsat** [comment]
After about 8 hours the training seems to be completed. 
This took quite long for just 250 samples.

App does not reply with correct intents for the given samples though. But as this is another problem I am closing my original bug report.

**Comment by l5t** [comment]
@hweiler I just restarted your training
