### ISSUE TITLE
Not unable to untrain or retrain text

### ISSUE THREAD

**Issue by khwstech** [wit-ai/wit#764]
Bug

I am using WIT via FB. For some reason I threw in the following random text:
asdfsdfsda

1st issue: WIt was understanding it as an entity called vehicleMake and returning value Mazda... 
2nd issue: I deleted this entity named vehicleMake and now when i entered asdfsdfsda WIT correctly didnt find any matches however when FB calls my API it still is passing vehicleMake as the NLP entity even though it no longer exists in my WIT

3rd issue: So to try and fix it i created an entity called ignore and value set to true. But now that is telling me : 'Could not validate this expression'

I would like it not to find any matches and it shouldnt be finding old entities via FBs link.

App ID:
59945ded-a991-458b-9458-1ea934a685af

**Comment by l5t** [comment]
Thanks for reporting. 
1st issue: this is probably because you validated some single word expressions as free-text entity for vehiculeMake. For example, if you validate just this expression "Mazda" or "Honda" as a example of a free-text/keyword entity, then Wit will try to guess other expression like this and there is no way to teach M that just the expression "blabla" is not a car. But when Wit guesses a entity value you will have the key suggested=true in the API output. That plus the confidence should help you
2nd issue: there may be a small lag. Can you still reproduce? If so please let us now how we can test  you FB call
3rd issue: please look at the first issue above for recommendation

**Comment by patapizza** [comment]
@khwstech Please follow what @l5t suggested. Feel free to reopen if you still experience the other issues.

**Comment by lmessinger** [comment]
i cannot untrain either. 

i tried to manually delete the expression used for training from https://wit.ai/<user name>/<app name>/entities/intent, Expressions section, to no avail. 

since we're building an app which allows training, its important - for debugging and control of users' input

any other ideas?

**Comment by stopachka** [comment]
ey lmessinger -- Do you mind telling me more about what problem you are having? (I am not sure how your last message relates to the initial problem)

**Comment by lmessinger** [comment]
actually it does untrain, i opened a different issue and closed it after a while - https://github.com/wit-ai/wit/issues/834
thanks for following up!
