### ISSUE TITLE
Questions about trait-entities, entity status, documentation updates

### ISSUE THREAD

**Issue by cognitivelutech** [wit-ai/wit#771]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
questions
**What is the current behavior?**
1. I am trying to understand the entities ["lookup search"](https://wit.ai/docs/recipes#which-entity-should-i-use), more in details, how to set the "trait" from code?

2. Can you please specify why the entity "intent" is used in the tutorial for several examples? when is it needed to create a new trait entity?

3. What about setting the status of an entity? can you provide a full programmatically example? documentation seems incomplete, it is not clear what is the exact consequence

4. the "complete documentation" still points several "old" sections (i.e. [create intents](https://wit.ai/docs/complete-guide#create-intents-link))

Thanks in advance :)

**Comment by l5t** [comment]
Intent is a trait entity. It is used in the tutorial for several examples because in most of apps, you want to detect the main intent (intention) of the user and having a trait entity to capture this is needed. But you're free to call it intent2, intention, goal,....

Not sure what you mean by setting the status of an entity. Do you mean setting the type of an entity? Defining the entity type has a consequence on how Wit extract the entities. https://wit.ai/blog/2017/08/23/clearer-controls-over-entity-lookup-strategies

Thanks also for reporting the link. It is normally only accessible from the deprecated doc
![image](https://user-images.githubusercontent.com/6992759/30253957-a355bd62-9644-11e7-8f85-1ca3b0532aec.png)
