### ISSUE TITLE
Majority of /speech requests return 400 (Bad Request)  (.wav files)

### ISSUE THREAD

**Issue by Krogsager** [wit-ai/wit#784]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Question
**What is the current behavior?**
Most of the time voice recordings send with `client.speech(strFilePath, None, {'Content-Type': 'audio/wav'})`, return  "400 (Bad Request)" 
Response time is ~1.2 seconds. Danish language. 
The files are less than 3 seconds and contain less than 50 characters of speech.
[recordings.zip](https://github.com/wit-ai/wit/files/1313559/recordings.zip)
Sample recordings are attached in the .zip. 

**What is the expected behavior?**
What went wrong? I expected a speech-to-text operation, or at least some indication of what happend.
Edit: I am speculating if it is a problem with the voice/noise ratio. Or volume.

**What is the App ID where you are experiencing this issue (if applicable)?**
59a94f2d-f77a-4644-bbda-0812536a0942

**Comment by stopachka** [comment]
We are debugging this as we speak. will update with more info as I dig deeper

**Comment by blandinw** [comment]
Hi @Krogsager, thanks for reporting this!
We looked at your audio files and the issue is probably the quality of the recordings (background noise, etc.). The Danish speech recognition engine simply does not "hear" human voice.

We could probably do a better job here with better models and better normalization though. We will be working with the FB speech recognition team to try and improve the situation going forward. Can't give a time estimate since this is not in our top priorities at the moment.
