### ISSUE TITLE
Feature Enhancement: Fixing / Mass Validating Samples

### ISSUE THREAD

**Issue by stopachka** [wit-ai/wit#787]
If a user makes a mistake with validating samples, there is no easy way to go back and clean them up.

They often need to export the app in order to do this. 

Perhaps we can create a UI for this.

**Comment by eorroe** [comment]
I think the solution to this would be batch editing.

If the UI could allow us to multi-select expressions, and do the following actions for each. Then we solve the problem.

- Add entity with value
- Remove multiple entities
- Replace multiple entity values

I think a modal popup with a grid selector of all entities from selected expressions would be the most intuitive UI for this, where we can select each all the entities to make an action on, like remove, replace.

Something like this (Where each number is an entity instead)
![grid selector](https://user-images.githubusercontent.com/6982605/30775417-0a2f99b0-a061-11e7-8ac2-7055a9b8f48e.png)

And then for adding entities, a UI that allows us to add multiple entities and values to set. With a confirm button at the bottom:

(Something like this, didn't find example with confirm button)
![image](https://user-images.githubusercontent.com/6982605/30775470-31c5e69a-a062-11e7-8cf5-74b4e5bf33be.png)


**This would be a huge plus since we can already filter by values, but applying these actions would save us huge amount of time**
