### ISSUE TITLE
NO log and inbox

### ISSUE THREAD

**Issue by trimethylxanthine** [wit-ai/wit#808]
Hi, my bot doesn't show any logs and inbox items anymore since yesterday. I have even tried to create a new app and imported the "old" bot data. 

cURL gives good responses and shows the entities with the confidence level. But i want to track every input through the log and inbox

My app id: 59d3fb6e-4696-468e-b49e-4828ff9f24c2

Thanks for the help

**Comment by blandinw** [comment]
@trimethylxanthine, thanks for reporting this issue.

We had a temporary issue with our queueing system (which we're in the process of replacing for something more robust) which prevented logs to be processed. The system is back online now.

We do apologize for the inconvenience. Feel free to reopen if the issue is not fixed.
