### ISSUE TITLE
Intent is not detected even with the exact string

### ISSUE THREAD

**Issue by touchaponk** [wit-ai/wit#809]
**bug**
App ID: 59d4a7ad-5b17-4080-bcb7-8fddfad959d4

1. I created a new intent with several trait values. One of them (value: ask_for) contains an exact word "สวัสดี" (i.e. "Hello" in Thai) .
2. I typed in "สวัสดี" into the test console and it still can't find any intent/entity

PS. Bot is already set to Thai language

**Comment by blandinw** [comment]
@touchaponk, thanks for reporting this issue.

We had a temporary issue with our queueing system (which we're in the process of replacing for something more robust) which prevented your requests to be processed. The system is back online now. Could you try again?

We do apologize for the inconvenience. Feel free to reopen if the issue is not fixed.
