### ISSUE TITLE
Not able to add strings to the entities

### ISSUE THREAD

**Issue by phanindra2767** [wit-ai/wit#810]
My APPID : 59b27a85-fcfc-4499-9e83-378bf5e7db08

see the below picture
![image](https://user-images.githubusercontent.com/32517936/31181827-e1abe52e-a93f-11e7-9cd2-5c516da4e941.png)
i trained "nearby banks" with findATMS but when i am tested i am getting intent null.

**Comment by l5t** [comment]
We had an issue with the training. It should be better now.

**Comment by blandinw** [comment]
@phanindra2767, thanks for reporting this issue.
 
We had a temporary issue with our queueing system (which we're in the process of replacing for something more robust) which prevented your requests to be processed. The system is back online now.

We do apologize for the inconvenience. Feel free to reopen if the issue is not fixed.
