### ISSUE TITLE
Inconsistent speech recognition results

### ISSUE THREAD

**Issue by carloalbertobarbano** [wit-ai/wit#822]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug

**What is the current behavior?**
On the same audio file, wit returns inconsistent results. Sometimes speech recognition works fine, while other times wit returns 'bad-request'

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
There isn't really a sequence of steps to reproduce it, it randomly happens. Here's the log from wit on the same audio file (language is italian): 

Attempt n. 1: _{'code': 'bad-request', 'error': 'Bad request'}_
Attempt n. 2, one minute later:  _{'\_text': 'prova prova', 'entities': {}, 'msg_id': '0MQYrlnEuhUvy7T4N'}_

Here's my post request: 
```
Url: https://api.wit.ai/speech`
Authorization: 'Bearer <token>' 
Content-Type: 'audio/raw; encoding=signed-integer; bits=16; rate=8000; endian=little'
```
and, for completeness, the python code (using requests module)

```python

# Long audio files (> 20s) are splitted in shorter chunks. 
# The test file I am referring to above is 2s long, so it is sent as a whole
# Every chunk is correctly encoded to bits=16, rate=8000, endian=little

wit_url = 'https://api.wit.ai/speech'
headers = {'Authorization': 'Bearer ' + auth.wit_key[lang],
           'Content-Type': 'audio/raw; encoding=signed-integer; bits=16; rate=8000; endian=little'}

for chunk in chunks:
  request = requests.post(wit_url, headers=headers, data=chunk.raw_data)
  res = request.json()
  pprint.pprint(res)
```

**What is the expected behavior?**
Should get the same result among multiple calls on the same audio files, either 'bad-request' or empty text, if the recognition was unsuccessful, or the recognized text.
Please note that I am not referring to speech recognition accuracy. 

**What is the App ID where you are experiencing this issue (if applicable)?**
58359196-6d19-46be-991f-1a11d389325a

**Comment by blandinw** [comment]
@carloalbertobarbano Thank you for your feedback!
It does sound like a bug, could you provide us with the audio file so that we can more easily reproduce?

**Comment by carloalbertobarbano** [comment]
This issue does not happen with this file only, but here it is (had to .zip as .3gpp is not supported by github)

[wit-audiofile.zip](https://github.com/wit-ai/wit/files/1392273/wit-audiofile.zip)

**Comment by blandinw** [comment]
Hmm, I consistently get `{'code': 'bad-request', 'error': 'Bad request'}` with this audio file (tested ~20 times at various time intervals between 1 min and 1 hour).

Do you have a more solid repro?

**Comment by carloalbertobarbano** [comment]
That's probably because the .3gpp file is not encoded correctly by default. If you are trying it with python then you can use pydub to encode it correctly 

```python
sound = AudioSegment.from_ogg("filename.3gpp")
sound = sound.set_sample_width(2)
sound = sound.set_channels(1)
sound = sound.set_frame_rate(8000)
```

This is how I do it, and it does get recognized but *not always*.

If you are able to see wit logs, can you explain more what causes the 'bad-request' error? It would be useful to have a short description saying what's causing a specific error (i.e. bad encoding, timeout, etc), bad-request could mean a lot of things.

I can try collecting more sample audio files if you need them. 
My app is dealing with different audio formats, (3gp, m4a, ogg, opus, etc) and they all get encoded the same way before being sent to wit. 
However, the problem I encounter is always the same. 
At first I thought there was a bug in my application, but as this happens on a same audio file too, that lead me to think it's a problem on wit's side.

**Comment by carloalbertobarbano** [comment]
@blandinw do you have any news?

**Comment by stopachka** [comment]
@carloalbertobarbano we're on it, will let you know as we get info

**Comment by datspike** [comment]
I think I'm having the same problems as OP
**Do you want to request a feature, report a bug, or ask a question about wit?**
Bug

**What is the current behavior?**
On the same audio file, wit returns inconsistent results. Sometimes speech recognition works fine, while other times wit returns 'bad-request' or 'internal server error'

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I'm trying to recognize the next file (MP3, 9 seconds length), from 3 attempts to recognize the file only 3 of them was successful, one of them was error 500 (internal error) and one 400 (bad request).
The ratio between successful and not successful requests (either 400 or 500 error) in inconsistent. 
[wit_test.zip](https://github.com/wit-ai/wit/files/1444196/wit_test.zip)

**What is the expected behavior?**
Should get the same result among multiple calls on the same audio files, either 'bad-request' or empty text, if the recognition was unsuccessful, or the recognized text.

**What is the App ID where you are experiencing this issue (if applicable)?**
5942c9e6-1ede-4781-9cb1-2087a614d890

I'm also experiencing very long server response time, it was roughly <length_of_audio>/3 before the errors started and it is a lot bigger (sorry, no exact data data)

**Comment by AvielNiego** [comment]
I have the same problemwith  `pywit` which is the python library for WitAi

For couple of days I've been using `pywit` in my app, which has 5K~ uses per day.
Until today everything worked perfect.

This is my code:
`
Wit('TOKEN').speech(open('file.wav', 'rb').read(), headers={'Content-Type': 'audio/wav'})['_text']
`
For a couple of hours now, I sometimes get this error:

> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
>   File "C:\Develop\XXX\wit_ai_client.py", line 14, in recognize
>     return Wit(XXX).speech(wav_content, headers={'Content-Type': 'audio/wav'})['_text']
>   File "C:\Python35\lib\site-packages\wit\wit.py", line 102, in speech
>     data=audio_file, headers=headers)
>   File "C:\Python35\lib\site-packages\wit\wit.py", line 41, in req
>     ' (' + rsp.reason + ')')
> wit.wit.WitError: Wit responded with status: 400 (Bad Request)

Sometimes the translation return just right, but sometimes `pywit` throws this error

The app id is: 59f30c07-1f08-4c0f-90ac-ad61a7e22662

**Comment by datspike** [comment]
Tried to do the same with `curl`, seems like Wit is unhappy about all of my files which were valid and working before. I've tried this with either ffmpeg-encoded mp3's and wav files with default settings.
`"error" : "Mismatch between the provided content-type and the bytes you sent.\nAre you sure it's a valid sound file?",
"code" : "content-type-mismatch"`

**Comment by blandinw** [comment]
Thanks for your feedback and patience, I'm looking into it

**Comment by ArBohe** [comment]
same behaviour.... gets through once in a while. rest of the time is bad request. never had issues before... :(

**Comment by patapizza** [comment]
@ArBohe Do you still experience the issue?

**Comment by ArBohe** [comment]
Je n’ai pas vérifié ce soir. J’essaye demain matin et je confirme/infirme :)
Merci,Arnaud
		
		

		Cheers,Arnaud
	




On Fri, Dec 29, 2017 at 9:58 PM +0100, "Julien Odent" <notifications@github.com> wrote:












@ArBohe Do you still experience the issue?

**Comment by ArBohe** [comment]
Hey - Happy new year / bonne Année 2018! and sorry for not coming back earlier.
The issue seems resolved ! 

Thanks very much guys
Arnaud


De: Odent Julien <notifications@github.com>
Répondre: wit-ai/wit <reply@reply.github.com>
Date: 29 décembre 2017 at 21:58:13
À: wit-ai/wit <wit@noreply.github.com>
Cc: ArBohe <arnaud@bohelay.com>, Mention <mention@noreply.github.com>
Sujet:  Re: [wit-ai/wit] Inconsistent speech recognition results (#822)  

@ArBohe Do you still experience the issue?

**Comment by blandinw** [comment]
I cannot repro this issue anymore. We'll make a pass at speech reliability issues at some point, but this is not a priority as of today.

**Comment by farooqkz** [comment]
@blandinw
I have the same problem.code:
```python
import wit
a = wit.Wit("my token")
with open("3.wav", "rb") as fp:
    b = a.speech(fp, None, {"Content-type": "audio/wav"})
```
output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in f
  File "/home/farooqkz/.local/lib/python3.6/site-packages/wit/wit.py", line 88, in speech
    data=audio_file, headers=headers)
  File "/home/farooqkz/.local/lib/python3.6/site-packages/wit/wit.py", line 41, in req
    ' (' + rsp.reason + ')')
wit.wit.WitError: Wit responded with status: 400 (Bad Request)
```
Sound file attached.
[3.zip](https://github.com/wit-ai/wit/files/3076613/3.zip)

**Comment by patapizza** [comment]
Hi @farooqkz, please open up a new ticket for new issues, it's easier to track.
Can you try using the API directly with curl to get more details? 400s are client-side issues.
