### ISSUE TITLE
Speech API speeds are way too slow

### ISSUE THREAD

**Issue by cloudratha** [wit-ai/wit#843]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
BUG

**What is the current behavior?**
Speech API response times are too long, over 30s in my case.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
curl -XPOST 'https://api.wit.ai/speech?v=20170307'    -i -L    -H "Authorization: Bearer $TOKEN"    -H "Content-Type: audio/wav"    --data-binary "@audio.wav"

**What is the expected behavior?**
Usable response times

**What is the App ID where you are experiencing this issue (if applicable)?**
59faf79d-bfd3-4661-8f73-c5235757b152

**Comment by sylmanu** [comment]
@cloudratha, I can't agree more with you! We've been reporting this issue for few months now but it seems that they are in the process of moving their whole infra to facebook and we shouldn't be expecting improvements soon... Hope it helps...

**Comment by blandinw** [comment]
@cloudratha @sylmanu We sincerely apologize for the inconvenience.

Due to bad actors on the platform, some shards experience slow downs.
We're aware of the problem and are constantly implementing counter-measures to detect and stop these bad actors. This is why we can't have nice things. I'll close the issue, but please reopen one if this happens again.
