### ISSUE TITLE
[Question] Default entity return

### ISSUE THREAD

**Issue by kjanko** [wit-ai/wit#854]
Hello,

is there a way to make Wit.ai return a default entity (intent) if no entity is detected?

**Comment by stopachka** [comment]
Hey there, you could try to train Wit to do this, but I'd suggest simply checking if there are no entities in the response. 

Could you tell us more about your use case?

**Comment by kjanko** [comment]
@stopachka It's not a big deal, It's just the fact that implementation wise there's less code to write if there's a default entity.

**Comment by stopachka** [comment]
This can get a bit complex, because confidently returning no entity found is not quite the same as returning no entities. i.e no entities could mean that there was some other issue, so both cases would need to be handled. 

Will close for now, but keep this in mind for future api enhancements! Thanks for the input @kjanko!
