### ISSUE TITLE
Is wit.ai shutting down the bot engine?

### ISSUE THREAD

**Issue by chenprogrammer** [wit-ai/wit#899]
I saw the news about it.
https://techcrunch.com/2017/07/27/wit-ai-is-shutting-down-bot-engine-as-facebook-rolls-nlp-into-its-updated-messenger-platform/

When will you shut it down?
Can I still use wit.ai to create a bot?
There is no story option on wit.ai website.

**Comment by l5t** [comment]
Indeed we are deprecating Stories and will focus on the NLP API: https://wit.ai/blog/2017/07/27/sunsetting-stories
So I would suggest using /message + code on your side to manage the conversation/answer instead if you were to use Stories: https://github.com/wit-ai/wit-stories-migration-tutorial

**Comment by hactar** [comment]
Just to add because many people who are new to wit.ai I talk to don't know the difference:

Wit.ai is NOT shutting down, you will still be able to use bots based on the /message API and to create new bots.

Whats shutting down is the bot ENGINE, a wit feature that allowed to to create stories in a web interface instead of in your own code. You now have to create stories in your own code, but you can still use wit.ai for NLP.

**Comment by l5t** [comment]
Great clarification by our one and only Hactar!
