### ISSUE TITLE
"this week" should return time interval and not a date by wit:date/time entity.

### ISSUE THREAD

**Issue by bilalchaglani** [wit-ai/wit#918]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
Bug
**What is the current behavior?**
Returns the date of monday.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
My app gives event information to its users. So when somebody queries about events of a week, it returns only the gig for monday. Time interval would be of great help.
**What is the expected behavior?**
Return a time interval between monday to friday.
**What is the App ID where you are experiencing this issue (if applicable)?**
57cfc3bb-1079-45a5-93b5-6d6998f581ca

**Comment by AntoineEsteve** [comment]
I am new with wit, but the `wit/datetime` entity does return dates or intervals based on the expression. When it returns a date, there is also a property "grain". If you always want an interval you can convert the date to an interval using the grain.  

With "last week" it does return the date of monday but with a "week" grain:

![image](https://user-images.githubusercontent.com/11315805/34830322-d23f2e4c-f6e3-11e7-9a8c-cf847dac7a66.png)

Note: If you type "since last week" if will return an interval

**Comment by patapizza** [comment]
As @AntoineEsteve said, the `grain` information is what you're looking for. See [the docs](https://wit.ai/docs/http/20170307#response-format-link) for more details on the `wit/datetime` format.
