### ISSUE TITLE
Adding Custom Training to wit/greetings

### ISSUE THREAD

**Issue by PatroxGaurab** [wit-ai/wit#958]
I'm trying to train the model with text "hy" for wit/greetings intent. But it is responding with blank entities {} even after training.

**Comment by stopachka** [comment]
Hey @PatroxGaurab , because greetings is a builtin entity, it trains more slowly, and considers the whole dataset. 

I am not sure "hy" is something that is generally considered a greeting entity. I would suggest you make a `custom_greeting` entity, and train that as well. This way you can have an app-specific greeting, alongside wit/greeting
