### ISSUE TITLE
How Learning works for similarly phrased intents

### ISSUE THREAD

**Issue by paulopadopalos** [wit-ai/wit#979]
**Do you want to request a *feature*, report a *bug*, or ask a *question* about wit?**
This is a question.

Imagine a scenario where a bot answers two types of query which are worded in the same way but involve different entities. For example:

"Where is the {**building**}?" might invoke a lookup to return a map showing the location of a building entity.

"Where is the {**meeting**}?" might invoke a lookup of scheduled events, returning the room where a meeting has been scheduled along with a day and time.

I can see two approaches to representing this in Wit:

1. We could have two different intents, **findBuilding** and **findMeeting**.
2. We could have a general intent, **findSomething** which then looks at the entities involved and decides what specific action to take.

As a developer, Option 1 is preferable because it means writing less code. However, I'm worried I may confuse my Wit model by having two intents which differ only by the entities involved.

**So my question is, is Wit "smart" enough to learn that two intents are different if they only differ by the entities involved?** Or should we get better results treating this as one intent and handling the different scenarios in our own code?

**Comment by stopachka** [comment]
Hey @paulopadopalos , 

Wit could learn `findMeeting` and `findBuilding`, but they would often be conflicting with eachother, and you may need more data to train both of them about structure of the sentences. 

I would think `findSomething` would be a better approach, because it let's your entity become more flexible. i.e if a user says `where is the telephone`, it can be easily extended, and the training data for positioning can be shared. 


Could you elaborate more on why the second approach produces more code?

**Comment by paulopadopalos** [comment]
Hi @stopachka,

That sounds like Wit behaves as I suspected. I'll go with the `findSomething` approach.

The downside of this is that I then have to code up different scenarios based on what entities have been found... instead of having a simple `findMeeting` function and a separate `findBuilding` function, I'll end up with a single `findSomething` function which has to contain some if/then logic to determine which other functions should be called.

Not the end of the world. If Wit could have handled it, there would have been a few less `if` or `switch` statements in my code.
